# Generated by Django 4.2 on 2025-12-07 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("performance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="performancerecommendation",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="performancerecommendation",
            name="implemented_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="implemented_recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="performancemetric",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="performancealert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="performancealert",
            name="metric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="performance.performancemetric",
            ),
        ),
        migrations.AddField(
            model_name="performancealert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="performancealert",
            name="system_health",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="performance.systemhealth",
            ),
        ),
        migrations.AddField(
            model_name="dashboardwidget",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_widgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="performancerecommendation",
            index=models.Index(fields=["status"], name="performance_status_855c2d_idx"),
        ),
        migrations.AddIndex(
            model_name="performancerecommendation",
            index=models.Index(
                fields=["priority"], name="performance_priorit_b3374e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancerecommendation",
            index=models.Index(
                fields=["recommendation_type"], name="performance_recomme_10df01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancemetric",
            index=models.Index(
                fields=["metric_type", "-timestamp"],
                name="performance_metric__6526c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performancemetric",
            index=models.Index(
                fields=["service_name", "-timestamp"],
                name="performance_service_2b1587_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performancemetric",
            index=models.Index(
                fields=["-timestamp"], name="performance_timesta_139c00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancealert",
            index=models.Index(fields=["status"], name="performance_status_665ed2_idx"),
        ),
        migrations.AddIndex(
            model_name="performancealert",
            index=models.Index(
                fields=["alert_level"], name="performance_alert_l_2bd005_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancealert",
            index=models.Index(
                fields=["-triggered_at"], name="performance_trigger_9169ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardwidget",
            index=models.Index(
                fields=["created_by"], name="performance_created_0fdef3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardwidget",
            index=models.Index(
                fields=["is_active"], name="performance_is_acti_cf62a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardwidget",
            index=models.Index(
                fields=["widget_type"], name="performance_widget__f09f7f_idx"
            ),
        ),
    ]
