# Generated by Django 4.2 on 2025-11-20 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dashboardwidget',
            new_name='performance_created_0fdef3_idx',
            old_name='performanc_created_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardwidget',
            new_name='performance_is_acti_cf62a2_idx',
            old_name='performanc_is_acti_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardwidget',
            new_name='performance_widget__f09f7f_idx',
            old_name='performanc_widget_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='performancealert',
            new_name='performance_status_665ed2_idx',
            old_name='performanc_status_234567_idx',
        ),
        migrations.RenameIndex(
            model_name='performancealert',
            new_name='performance_alert_l_2bd005_idx',
            old_name='performanc_alert_l_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='performancealert',
            new_name='performance_trigger_9169ae_idx',
            old_name='performanc_trigger_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='performancemetric',
            new_name='performance_metric__6526c5_idx',
            old_name='performanc_metric_ty_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='performancemetric',
            new_name='performance_service_2b1587_idx',
            old_name='performanc_service__123456_idx',
        ),
        migrations.RenameIndex(
            model_name='performancemetric',
            new_name='performance_timesta_139c00_idx',
            old_name='performanc_timest_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='performancerecommendation',
            new_name='performance_status_855c2d_idx',
            old_name='performanc_status_345678_idx',
        ),
        migrations.RenameIndex(
            model_name='performancerecommendation',
            new_name='performance_priorit_b3374e_idx',
            old_name='performanc_priorit_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='performancerecommendation',
            new_name='performance_recomme_10df01_idx',
            old_name='performanc_recomme_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='systemhealth',
            new_name='performance_status_be631d_idx',
            old_name='performanc_status_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='systemhealth',
            new_name='performance_compone_ece23c_idx',
            old_name='performanc_compone_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='systemhealth',
            new_name='performance_last_ch_bf3760_idx',
            old_name='performanc_last_ch_123456_idx',
        ),
        migrations.AddField(
            model_name='performancealert',
            name='metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.performancemetric'),
        ),
        migrations.AddField(
            model_name='performancealert',
            name='system_health',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.systemhealth'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='performancealert',
            name='triggered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='performancerecommendation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='systemhealth',
            name='last_check',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
