# Generated by Django 4.2 on 2025-11-20 05:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0007_cashdrawer_cashtransaction_cashreconciliation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('transaction', 'Transaction Alert'), ('account', 'Account Alert'), ('user', 'User Alert'), ('system', 'System Alert')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], default='new', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fraud_score', models.PositiveIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('rule_details', models.JSONField(default=dict)),
                ('transaction_data', models.JSONField(default=dict)),
                ('account_data', models.JSONField(default=dict)),
                ('user_data', models.JSONField(default=dict)),
                ('investigation_notes', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('resolution_action', models.CharField(blank=True, max_length=100)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location_data', models.JSONField(default=dict)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.account')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_alerts', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('amount_threshold', 'Amount Threshold'), ('velocity_check', 'Velocity Check'), ('unusual_pattern', 'Unusual Pattern'), ('location_anomaly', 'Location Anomaly'), ('time_based', 'Time-Based Rule'), ('account_behavior', 'Account Behavior'), ('custom', 'Custom Rule')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('field', models.CharField(max_length=100)),
                ('operator', models.CharField(choices=[('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('eq', 'Equal'), ('ne', 'Not Equal'), ('contains', 'Contains'), ('not_contains', 'Does Not Contain'), ('regex', 'Regex Match')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('additional_conditions', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_block', models.BooleanField(default=False)),
                ('require_approval', models.BooleanField(default=True)),
                ('escalation_threshold', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.PositiveIntegerField(default=0)),
                ('false_positive_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fraud_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(choices=[('transaction_velocity', 'Transaction Velocity'), ('amount_pattern', 'Amount Pattern'), ('location_pattern', 'Location Pattern'), ('time_pattern', 'Time Pattern'), ('behavioral', 'Behavioral Pattern')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('conditions', models.JSONField()),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_occurrences', models.PositiveIntegerField(default=0)),
                ('fraud_occurrences', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-confidence_score'],
                'unique_together': {('pattern_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FraudCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('case_type', models.CharField(choices=[('transaction_fraud', 'Transaction Fraud'), ('account_takeover', 'Account Takeover'), ('identity_theft', 'Identity Theft'), ('money_laundering', 'Money Laundering'), ('internal_fraud', 'Internal Fraud'), ('system_compromise', 'System Compromise'), ('other', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('pending_review', 'Pending Review'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='open', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('estimated_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('actual_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('recovered_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('investigation_notes', models.TextField(blank=True)),
                ('evidence', models.JSONField(default=list)),
                ('timeline', models.JSONField(default=list)),
                ('resolution_type', models.CharField(blank=True, choices=[('confirmed_fraud', 'Confirmed Fraud'), ('false_positive', 'False Positive'), ('unable_to_determine', 'Unable to Determine'), ('prevented_loss', 'Loss Prevented'), ('recovered_funds', 'Funds Recovered'), ('other', 'Other')], max_length=50)),
                ('resolution_details', models.TextField(blank=True)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('assigned_investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_cases', to=settings.AUTH_USER_MODEL)),
                ('primary_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.account')),
                ('primary_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.transaction')),
                ('primary_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_cases', to=settings.AUTH_USER_MODEL)),
                ('related_alerts', models.ManyToManyField(blank=True, related_name='cases', to='fraud_detection.fraudalert')),
                ('related_transactions', models.ManyToManyField(blank=True, related_name='fraud_cases', to='banking.transaction')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='triggered_rules',
            field=models.ManyToManyField(related_name='alerts', to='fraud_detection.fraudrule'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fraudrule',
            index=models.Index(fields=['rule_type'], name='fraud_detec_rule_ty_167804_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudrule',
            index=models.Index(fields=['severity'], name='fraud_detec_severit_3ac147_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudrule',
            index=models.Index(fields=['is_active'], name='fraud_detec_is_acti_4b5072_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudcase',
            index=models.Index(fields=['status'], name='fraud_detec_status_ac8d39_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudcase',
            index=models.Index(fields=['priority'], name='fraud_detec_priorit_0c6cde_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudcase',
            index=models.Index(fields=['case_type'], name='fraud_detec_case_ty_4d2300_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudcase',
            index=models.Index(fields=['created_at'], name='fraud_detec_created_1998a7_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudcase',
            index=models.Index(fields=['case_number'], name='fraud_detec_case_nu_c5a70a_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['status'], name='fraud_detec_status_1f3b22_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['priority'], name='fraud_detec_priorit_e091f7_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['alert_type'], name='fraud_detec_alert_t_a739a0_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['created_at'], name='fraud_detec_created_9bad98_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['fraud_score'], name='fraud_detec_fraud_s_072a89_idx'),
        ),
    ]
