# Generated by Django 4.2 on 2025-12-07 15:08

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FraudAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("transaction", "Transaction Alert"),
                            ("account", "Account Alert"),
                            ("user", "User Alert"),
                            ("system", "System Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                            ("escalated", "Escalated"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("fraud_score", models.PositiveIntegerField(default=0)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("rule_details", models.JSONField(default=dict)),
                ("transaction_data", models.JSONField(default=dict)),
                ("account_data", models.JSONField(default=dict)),
                ("user_data", models.JSONField(default=dict)),
                ("investigation_notes", models.TextField(blank=True)),
                ("resolution", models.TextField(blank=True)),
                ("resolution_action", models.CharField(blank=True, max_length=100)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("location_data", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FraudAuditTrail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("correlation_id", models.CharField(db_index=True, max_length=255)),
                ("transaction_id", models.CharField(db_index=True, max_length=255)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("decision_data", models.TextField()),
                ("decision_hash", models.CharField(max_length=128)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("fraud_evaluation", "Fraud Evaluation"),
                            ("alert_creation", "Alert Creation"),
                            ("rule_trigger", "Rule Trigger"),
                            ("manual_review", "Manual Review"),
                            ("rollback", "Rollback Action"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("reverted", "Reverted"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("reverted_at", models.DateTimeField(blank=True, null=True)),
                ("revert_reason", models.TextField(blank=True)),
                ("compliance_standard", models.CharField(blank=True, max_length=50)),
                (
                    "data_classification",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("confidential", "Confidential"),
                            ("restricted", "Restricted"),
                        ],
                        default="confidential",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FraudCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("case_number", models.CharField(max_length=50, unique=True)),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("transaction_fraud", "Transaction Fraud"),
                            ("account_takeover", "Account Takeover"),
                            ("identity_theft", "Identity Theft"),
                            ("money_laundering", "Money Laundering"),
                            ("internal_fraud", "Internal Fraud"),
                            ("system_compromise", "System Compromise"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("pending_review", "Pending Review"),
                            ("closed", "Closed"),
                            ("escalated", "Escalated"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("summary", models.TextField(blank=True)),
                (
                    "estimated_loss",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "actual_loss",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "recovered_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("investigation_notes", models.TextField(blank=True)),
                ("evidence", models.JSONField(default=list)),
                ("timeline", models.JSONField(default=list)),
                (
                    "resolution_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("confirmed_fraud", "Confirmed Fraud"),
                            ("false_positive", "False Positive"),
                            ("unable_to_determine", "Unable to Determine"),
                            ("prevented_loss", "Loss Prevented"),
                            ("recovered_funds", "Funds Recovered"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("resolution_details", models.TextField(blank=True)),
                ("resolution_date", models.DateTimeField(blank=True, null=True)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("escalation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("tags", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FraudPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("transaction_velocity", "Transaction Velocity"),
                            ("amount_pattern", "Amount Pattern"),
                            ("location_pattern", "Location Pattern"),
                            ("time_pattern", "Time Pattern"),
                            ("behavioral", "Behavioral Pattern"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("conditions", models.JSONField()),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("total_occurrences", models.PositiveIntegerField(default=0)),
                ("fraud_occurrences", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-confidence_score"],
            },
        ),
        migrations.CreateModel(
            name="FraudRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("amount_threshold", "Amount Threshold"),
                            ("velocity_check", "Velocity Check"),
                            ("unusual_pattern", "Unusual Pattern"),
                            ("location_anomaly", "Location Anomaly"),
                            ("time_based", "Time-Based Rule"),
                            ("account_behavior", "Account Behavior"),
                            ("custom", "Custom Rule"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("field", models.CharField(max_length=100)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("gt", "Greater Than"),
                            ("gte", "Greater Than or Equal"),
                            ("lt", "Less Than"),
                            ("lte", "Less Than or Equal"),
                            ("eq", "Equal"),
                            ("ne", "Not Equal"),
                            ("contains", "Contains"),
                            ("not_contains", "Does Not Contain"),
                            ("regex", "Regex Match"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("additional_conditions", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_block", models.BooleanField(default=False)),
                ("require_approval", models.BooleanField(default=True)),
                ("escalation_threshold", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("trigger_count", models.PositiveIntegerField(default=0)),
                ("false_positive_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
