# Generated by Django 4.2 on 2025-12-07 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fraud_detection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("banking", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fraudrule",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_fraud_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fraudpattern",
            unique_together={("pattern_type", "name")},
        ),
        migrations.AddField(
            model_name="fraudcase",
            name="assigned_investigator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fraudcase",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fraudcase",
            name="escalated_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escalated_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fraudcase",
            name="primary_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="banking.account",
            ),
        ),
        migrations.AddField(
            model_name="fraudcase",
            name="primary_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="banking.transaction",
            ),
        ),
        migrations.AddField(
            model_name="fraudcase",
            name="primary_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fraud_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fraudcase",
            name="related_alerts",
            field=models.ManyToManyField(
                blank=True, related_name="cases", to="fraud_detection.fraudalert"
            ),
        ),
        migrations.AddField(
            model_name="fraudcase",
            name="related_transactions",
            field=models.ManyToManyField(
                blank=True, related_name="fraud_cases", to="banking.transaction"
            ),
        ),
        migrations.AddField(
            model_name="fraudcase",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fraudaudittrail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fraud_audit_trails_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fraudaudittrail",
            name="reverted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fraud_audit_trails_reverted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="banking.account",
            ),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="escalated_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escalated_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="banking.transaction",
            ),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="triggered_rules",
            field=models.ManyToManyField(
                related_name="alerts", to="fraud_detection.fraudrule"
            ),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fraud_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="fraudrule",
            index=models.Index(
                fields=["rule_type"], name="fraud_detec_rule_ty_167804_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudrule",
            index=models.Index(
                fields=["severity"], name="fraud_detec_severit_3ac147_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudrule",
            index=models.Index(
                fields=["is_active"], name="fraud_detec_is_acti_4b5072_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudcase",
            index=models.Index(fields=["status"], name="fraud_detec_status_ac8d39_idx"),
        ),
        migrations.AddIndex(
            model_name="fraudcase",
            index=models.Index(
                fields=["priority"], name="fraud_detec_priorit_0c6cde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudcase",
            index=models.Index(
                fields=["case_type"], name="fraud_detec_case_ty_4d2300_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudcase",
            index=models.Index(
                fields=["created_at"], name="fraud_detec_created_1998a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudcase",
            index=models.Index(
                fields=["case_number"], name="fraud_detec_case_nu_c5a70a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudaudittrail",
            index=models.Index(
                fields=["correlation_id", "created_at"],
                name="fraud_detec_correla_3ef34a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fraudaudittrail",
            index=models.Index(
                fields=["transaction_id", "created_at"],
                name="fraud_detec_transac_4f1d9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fraudaudittrail",
            index=models.Index(
                fields=["decision_type", "status"],
                name="fraud_detec_decisio_e1c9be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fraudaudittrail",
            index=models.Index(
                fields=["created_at", "expires_at"],
                name="fraud_detec_created_2b0e5c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fraudalert",
            index=models.Index(fields=["status"], name="fraud_detec_status_1f3b22_idx"),
        ),
        migrations.AddIndex(
            model_name="fraudalert",
            index=models.Index(
                fields=["priority"], name="fraud_detec_priorit_e091f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudalert",
            index=models.Index(
                fields=["alert_type"], name="fraud_detec_alert_t_a739a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudalert",
            index=models.Index(
                fields=["created_at"], name="fraud_detec_created_9bad98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudalert",
            index=models.Index(
                fields=["fraud_score"], name="fraud_detec_fraud_s_072a89_idx"
            ),
        ),
    ]
