# Generated by Django 4.2 on 2025-11-20 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fraud_detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_id', models.CharField(db_index=True, max_length=255)),
                ('transaction_id', models.CharField(db_index=True, max_length=255)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('decision_data', models.TextField()),
                ('decision_hash', models.CharField(max_length=128)),
                ('decision_type', models.CharField(choices=[('fraud_evaluation', 'Fraud Evaluation'), ('alert_creation', 'Alert Creation'), ('rule_trigger', 'Rule Trigger'), ('manual_review', 'Manual Review'), ('rollback', 'Rollback Action')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reverted', 'Reverted'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('revert_reason', models.TextField(blank=True)),
                ('compliance_standard', models.CharField(blank=True, max_length=50)),
                ('data_classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='confidential', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_audit_trails_created', to=settings.AUTH_USER_MODEL)),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_audit_trails_reverted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fraudaudittrail',
            index=models.Index(fields=['correlation_id', 'created_at'], name='fraud_detec_correla_3ef34a_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudaudittrail',
            index=models.Index(fields=['transaction_id', 'created_at'], name='fraud_detec_transac_4f1d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudaudittrail',
            index=models.Index(fields=['decision_type', 'status'], name='fraud_detec_decisio_e1c9be_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudaudittrail',
            index=models.Index(fields=['created_at', 'expires_at'], name='fraud_detec_created_2b0e5c_idx'),
        ),
    ]
