extends: ["spectral:oas"]
rules:
  paths-kebab-case:
    description: "Paths must be kebab-case."
    message: "{{property}} must be kebab-case (lower-case and separated with hyphens)."
    severity: warn
    given: "$.paths"
    then:
      field: "@key"
      function: pattern
      functionOptions:
        match: "^(\\/|[a-z0-9-]+|{[a-zA-Z0-9_-]+})+$"
