# Generated by Django 4.2 on 2025-11-20 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('active_sessions', models.PositiveIntegerField(default=0)),
                ('closed_sessions', models.PositiveIntegerField(default=0)),
                ('average_session_duration', models.DurationField(blank=True, null=True)),
                ('average_response_time', models.DurationField(blank=True, null=True)),
                ('average_first_response_time', models.DurationField(blank=True, null=True)),
                ('average_queue_time', models.DurationField(blank=True, null=True)),
                ('max_queue_time', models.DurationField(blank=True, null=True)),
                ('abandoned_sessions', models.PositiveIntegerField(default=0)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('average_messages_per_session', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_satisfaction', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('satisfaction_responses', models.PositiveIntegerField(default=0)),
                ('total_agents_online', models.PositiveIntegerField(default=0)),
                ('average_sessions_per_agent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Agent'), ('active', 'Active'), ('closed', 'Closed'), ('escalated', 'Escalated'), ('transferred', 'Transferred')], default='waiting', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(default='general', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('queue_position', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_wait_time', models.DurationField(blank=True, null=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('customer_satisfaction', models.PositiveIntegerField(blank=True, null=True)),
                ('assigned_cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chat_sessions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions_as_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_customer', 'Waiting for Customer'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('category', models.CharField(choices=[('account', 'Account Issues'), ('transaction', 'Transaction Problems'), ('technical', 'Technical Support'), ('billing', 'Billing Questions'), ('general', 'General Inquiry'), ('complaint', 'Complaint'), ('feature_request', 'Feature Request')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('resolution_time', models.DurationField(blank=True, null=True)),
                ('customer_satisfaction', models.PositiveIntegerField(blank=True, null=True)),
                ('customer_feedback', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('internal_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('chat_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_ticket', to='chat.chatsession')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Ticket Created'), ('assigned', 'Ticket Assigned'), ('status_changed', 'Status Changed'), ('updated', 'Ticket Updated'), ('closed', 'Ticket Closed'), ('reopened', 'Ticket Reopened')], max_length=20)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='chat.supportticket')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSessionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Session Created'), ('assigned', 'Cashier Assigned'), ('transferred', 'Session Transferred'), ('escalated', 'Session Escalated'), ('closed', 'Session Closed'), ('reopened', 'Session Reopened')], max_length=20)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='chat.chatsession')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('file', 'File Attachment'), ('system', 'System Message'), ('typing', 'Typing Indicator')], default='text', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('file_size', models.PositiveIntegerField()),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=20)),
                ('mime_type', models.CharField(max_length=100)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('virus_scanned', models.BooleanField(default=False)),
                ('scan_result', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chat.chatmessage')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatanalytics',
            index=models.Index(fields=['date'], name='chat_chatan_date_5a7930_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatanalytics',
            unique_together={('date',)},
        ),
        migrations.AddIndex(
            model_name='supportticketaudit',
            index=models.Index(fields=['ticket'], name='chat_suppor_ticket__578916_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketaudit',
            index=models.Index(fields=['action'], name='chat_suppor_action_d46fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketaudit',
            index=models.Index(fields=['performed_by'], name='chat_suppor_perform_92c7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketaudit',
            index=models.Index(fields=['performed_at'], name='chat_suppor_perform_8e9969_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status'], name='chat_suppor_status_5a24c9_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['priority'], name='chat_suppor_priorit_4a4803_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['category'], name='chat_suppor_categor_48562d_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to'], name='chat_suppor_assigne_5b1c29_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['created_by'], name='chat_suppor_created_482fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['created_at'], name='chat_suppor_created_e87894_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsessionaudit',
            index=models.Index(fields=['session'], name='chat_chatse_session_62e85d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsessionaudit',
            index=models.Index(fields=['action'], name='chat_chatse_action_32f177_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsessionaudit',
            index=models.Index(fields=['performed_by'], name='chat_chatse_perform_f577d3_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsessionaudit',
            index=models.Index(fields=['performed_at'], name='chat_chatse_perform_3679b6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['status'], name='chat_chatse_status_97fce8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['priority'], name='chat_chatse_priorit_2bcebb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['assigned_cashier'], name='chat_chatse_assigne_da8b04_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['customer'], name='chat_chatse_custome_9ee417_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['started_at'], name='chat_chatse_started_d7f3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['last_message_at'], name='chat_chatse_last_me_6912f7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'timestamp'], name='chat_chatme_session_e81882_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender'], name='chat_chatme_sender__3a9411_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_read'], name='chat_chatme_is_read_24fa80_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['timestamp'], name='chat_chatme_timesta_f0eb7d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatfile',
            index=models.Index(fields=['message'], name='chat_chatfi_message_f8fd3b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatfile',
            index=models.Index(fields=['file_type'], name='chat_chatfi_file_ty_7f2651_idx'),
        ),
        migrations.AddIndex(
            model_name='chatfile',
            index=models.Index(fields=['virus_scanned'], name='chat_chatfi_virus_s_9f57ba_idx'),
        ),
    ]
