# Generated by Django 4.2 on 2025-12-07 15:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssignmentHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("change_type", models.CharField(max_length=50)),
                ("old_value", models.JSONField(blank=True, default=dict)),
                ("new_value", models.JSONField(blank=True, default=dict)),
                ("change_reason", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(default=datetime.datetime.now)),
                ("location", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientKYC",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_name", models.CharField(max_length=255)),
                ("client_id", models.CharField(max_length=50, unique=True)),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("submitted_at", models.DateTimeField(default=datetime.datetime.now)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("documents", models.JSONField()),
                ("geotag", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "commission_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit Commission"),
                            ("withdrawal", "Withdrawal Commission"),
                            ("transfer", "Transfer Commission"),
                            ("loan", "Loan Commission"),
                            ("other", "Other Commission"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("reassigned", "Reassigned"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(default=datetime.datetime.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assignment_location",
                    models.CharField(
                        blank=True,
                        help_text="Geotag when assignment was made",
                        max_length=100,
                    ),
                ),
                (
                    "last_location",
                    models.CharField(
                        blank=True,
                        help_text="Last known location of mobile banker",
                        max_length=100,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("estimated_completion", models.DateTimeField(blank=True, null=True)),
                ("actual_completion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("office_supplies", "Office Supplies"),
                            ("utilities", "Utilities"),
                            ("rent", "Rent"),
                            ("salaries", "Salaries"),
                            ("marketing", "Marketing"),
                            ("maintenance", "Maintenance"),
                            ("insurance", "Insurance"),
                            ("travel", "Travel"),
                            ("training", "Training"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date_incurred", models.DateField()),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receipt_url", models.URLField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-date_incurred"],
            },
        ),
        migrations.CreateModel(
            name="FieldCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("collected_at", models.DateTimeField(default=datetime.datetime.now)),
                ("location", models.CharField(max_length=100)),
                ("data", models.JSONField()),
                ("status", models.CharField(default="Collected", max_length=50)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("loan_follow_up", "Loan Follow-up"),
                            ("account_opening", "Account Opening"),
                            ("savings_collection", "Savings Collection"),
                            ("payment_collection", "Payment Collection"),
                            ("kyc_update", "KYC Update"),
                            ("general_inquiry", "General Inquiry"),
                            ("loan_application", "Loan Application"),
                            ("client_onboarding", "Client Onboarding"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                ("actual_start_time", models.DateTimeField(blank=True, null=True)),
                ("actual_end_time", models.DateTimeField(blank=True, null=True)),
                ("completion_notes", models.TextField(blank=True)),
                ("geotag", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["scheduled_date", "scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField()),
                ("required_role", models.CharField(max_length=100)),
                ("is_required", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="operations.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
