# Generated by Django 4.2 on 2025-12-07 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("banking", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="visitschedule",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_visits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="visitschedule",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_visits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="loan_application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="banking.loanapplication",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sent_operation_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fieldcollection",
            name="client_kyc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field_collections",
                to="operations.clientkyc",
            ),
        ),
        migrations.AddField(
            model_name="fieldcollection",
            name="collected_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="recorded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="customerassignment",
            name="assigned_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerassignment",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_customers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerassignment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="earned_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commissions_earned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commissions",
                to="banking.transaction",
            ),
        ),
        migrations.AddField(
            model_name="clientkyc",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_kyc",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clientkyc",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="clientkyc",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="operations.workflow",
            ),
        ),
        migrations.AddField(
            model_name="assignmenthistory",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="operations.customerassignment",
            ),
        ),
        migrations.AddField(
            model_name="assignmenthistory",
            name="changed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workflowstep",
            unique_together={("workflow", "order")},
        ),
        migrations.AddIndex(
            model_name="visitschedule",
            index=models.Index(
                fields=["scheduled_date"], name="operations__schedul_0ef659_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitschedule",
            index=models.Index(fields=["status"], name="operations__status_b80dde_idx"),
        ),
        migrations.AddIndex(
            model_name="visitschedule",
            index=models.Index(
                fields=["assigned_to"], name="operations__assigne_309e58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitschedule",
            index=models.Index(
                fields=["purpose"], name="operations__purpose_0f8a26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["-created_at"], name="operations__created_3ea26e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["is_read"], name="operations__is_read_e98f8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["recipient"], name="operations__recipie_ddb59c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["loan_application"], name="operations__loan_ap_094a8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["-date_incurred"], name="operations__date_in_1b304c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["category"], name="operations__categor_a34e0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["is_approved"], name="operations__is_appr_ab94f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerassignment",
            index=models.Index(
                fields=["customer"], name="operations__custome_262e15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerassignment",
            index=models.Index(
                fields=["assigned_to"], name="operations__assigne_fbcf46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerassignment",
            index=models.Index(fields=["status"], name="operations__status_2248b9_idx"),
        ),
        migrations.AddIndex(
            model_name="customerassignment",
            index=models.Index(
                fields=["assigned_at"], name="operations__assigne_55a667_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customerassignment",
            unique_together={("customer", "assigned_to")},
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(
                fields=["-created_at"], name="operations__created_91371b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(
                fields=["commission_type"], name="operations__commiss_9660d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(
                fields=["earned_by"], name="operations__earned__0bb50c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignmenthistory",
            index=models.Index(
                fields=["assignment", "-changed_at"],
                name="operations__assignm_f737d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignmenthistory",
            index=models.Index(
                fields=["changed_by"], name="operations__changed_c81d42_idx"
            ),
        ),
    ]
