# Generated by Django 4.2 on 2025-10-16 04:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0003_feestructure_transaction_description_and_more'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_type', models.CharField(choices=[('deposit', 'Deposit Commission'), ('withdrawal', 'Withdrawal Commission'), ('transfer', 'Transfer Commission'), ('loan', 'Loan Commission'), ('other', 'Other Commission')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.TextField(blank=True)),
                ('earned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions_earned', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='banking.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['-created_at'], name='operations__created_91371b_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['commission_type'], name='operations__commiss_9660d4_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['earned_by'], name='operations__earned__0bb50c_idx'),
        ),
    ]
