# Generated by Django 4.2 on 2025-10-16 16:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0002_commission_commission_operations__created_91371b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('office_supplies', 'Office Supplies'), ('utilities', 'Utilities'), ('rent', 'Rent'), ('salaries', 'Salaries'), ('marketing', 'Marketing'), ('maintenance', 'Maintenance'), ('insurance', 'Insurance'), ('travel', 'Travel'), ('training', 'Training'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_incurred', models.DateField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_incurred'],
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['-date_incurred'], name='operations__date_in_1b304c_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='operations__categor_a34e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_approved'], name='operations__is_appr_ab94f9_idx'),
        ),
    ]
