# Generated by Django 4.2 on 2025-10-16 17:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0003_expense_expense_operations__date_in_1b304c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('purpose', models.CharField(choices=[('loan_follow_up', 'Loan Follow-up'), ('account_opening', 'Account Opening'), ('savings_collection', 'Savings Collection'), ('payment_collection', 'Payment Collection'), ('kyc_update', 'KYC Update'), ('general_inquiry', 'General Inquiry'), ('loan_application', 'Loan Application'), ('client_onboarding', 'Client Onboarding')], max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('geotag', models.CharField(blank=True, max_length=100)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_visits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.AddIndex(
            model_name='visitschedule',
            index=models.Index(fields=['scheduled_date'], name='operations__schedul_0ef659_idx'),
        ),
        migrations.AddIndex(
            model_name='visitschedule',
            index=models.Index(fields=['status'], name='operations__status_b80dde_idx'),
        ),
        migrations.AddIndex(
            model_name='visitschedule',
            index=models.Index(fields=['assigned_to'], name='operations__assigne_309e58_idx'),
        ),
        migrations.AddIndex(
            model_name='visitschedule',
            index=models.Index(fields=['purpose'], name='operations__purpose_0f8a26_idx'),
        ),
    ]
