# Generated by Django 4.2 on 2025-11-20 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='servicerequest',
            new_name='services_se_member__fc23ab_idx',
            old_name='services_se_member_i_123456',
        ),
        migrations.RenameIndex(
            model_name='servicerequest',
            new_name='services_se_status_f1d047_idx',
            old_name='services_se_status__123456',
        ),
        migrations.RenameIndex(
            model_name='servicerequest',
            new_name='services_se_request_86219e_idx',
            old_name='services_se_request_123456',
        ),
        migrations.AlterField(
            model_name='checkbookrequest',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Delivery address if not pickup'),
        ),
        migrations.AlterField(
            model_name='checkbookrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of checkbooks requested'),
        ),
        migrations.AlterField(
            model_name='checkbookrequest',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Special printing instructions'),
        ),
        migrations.AlterField(
            model_name='loaninforequest',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Notes about information delivery'),
        ),
        migrations.AlterField(
            model_name='loaninforequest',
            name='loan_account_number',
            field=models.CharField(help_text='Loan account number', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='member',
            field=models.ForeignKey(help_text='Member requesting the service', on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requested_by',
            field=models.ForeignKey(help_text='Staff member who created the request', on_delete=django.db.models.deletion.CASCADE, related_name='created_service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='statementrequest',
            name='account_number',
            field=models.CharField(blank=True, help_text='Specific account number', max_length=50),
        ),
        migrations.AlterField(
            model_name='statementrequest',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date for custom statements', null=True),
        ),
        migrations.AlterField(
            model_name='statementrequest',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date for custom statements', null=True),
        ),
    ]
