# Generated by Django 4.2 on 2025-12-07 15:08

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("savings", "Savings Account"),
                            ("checking", "Checking Account"),
                            ("loan", "Loan"),
                            ("credit_card", "Credit Card"),
                            ("investment", "Investment"),
                            ("insurance", "Insurance"),
                            ("service", "Service"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "annual_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("min_age", models.IntegerField(default=18)),
                (
                    "min_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("membership_required", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("available_online", models.BooleanField(default=True)),
                ("available_in_branch", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_featured", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Product Categories",
            },
        ),
        migrations.CreateModel(
            name="ProductRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("cross_sell", "Cross-Sell"),
                            ("up_sell", "Up-Sell"),
                            ("retention", "Retention"),
                            ("engagement", "Engagement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("priority_score", models.IntegerField(default=0)),
                ("reasoning", models.TextField(blank=True)),
                ("transaction_context", models.JSONField(blank=True, default=dict)),
                ("customer_profile", models.JSONField(blank=True, default=dict)),
                ("is_viewed", models.BooleanField(default=False)),
                ("is_interested", models.BooleanField(blank=True, null=True)),
                ("is_applied", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-priority_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage Discount"),
                            ("fixed_amount", "Fixed Amount Discount"),
                            ("fee_waiver", "Fee Waiver"),
                            ("bonus_rate", "Bonus Interest Rate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "eligibility_type",
                    models.CharField(
                        choices=[
                            ("all_members", "All Members"),
                            ("new_members", "New Members Only"),
                            ("existing_members", "Existing Members Only"),
                            ("balance_threshold", "Balance Threshold"),
                            ("transaction_count", "Transaction Count"),
                            ("age_range", "Age Range"),
                            ("custom", "Custom Criteria"),
                        ],
                        default="all_members",
                        max_length=20,
                    ),
                ),
                ("eligibility_criteria", models.JSONField(blank=True, default=dict)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("max_uses", models.IntegerField(blank=True, null=True)),
                ("uses_count", models.IntegerField(default=0)),
                ("per_customer_limit", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PromotionUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("transaction_type", models.CharField(max_length=50)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-applied_at"],
            },
        ),
    ]
