# Generated by Django 4.2 on 2025-12-07 15:08

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIRateLimit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("user", "Per User"),
                            ("ip", "Per IP Address"),
                            ("global", "Global"),
                            ("endpoint", "Per Endpoint"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "endpoint_pattern",
                    models.CharField(
                        help_text="Regex pattern for matching endpoints", max_length=200
                    ),
                ),
                ("methods", models.JSONField(blank=True, default=list)),
                ("requests_per_unit", models.IntegerField(default=100)),
                (
                    "time_unit",
                    models.CharField(
                        choices=[
                            ("second", "Per Second"),
                            ("minute", "Per Minute"),
                            ("hour", "Per Hour"),
                            ("day", "Per Day"),
                        ],
                        default="minute",
                        max_length=10,
                    ),
                ),
                ("burst_limit", models.IntegerField(default=10)),
                (
                    "action_on_limit",
                    models.CharField(
                        choices=[
                            ("block", "Block Request"),
                            ("delay", "Delay Request"),
                            ("log", "Log Only"),
                        ],
                        default="block",
                        max_length=20,
                    ),
                ),
                ("block_duration", models.IntegerField(default=60)),
                ("exempt_users", models.JSONField(blank=True, default=list)),
                ("exempt_ips", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint", models.CharField(max_length=200)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("request_size", models.PositiveIntegerField(default=0)),
                ("response_size", models.PositiveIntegerField(default=0)),
                ("status_code", models.IntegerField()),
                (
                    "response_time",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("api_version", models.CharField(default="v1", max_length=10)),
                ("user_role", models.CharField(max_length=20)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="HealthCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("component_name", models.CharField(max_length=100)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("api", "API"),
                            ("database", "Database"),
                            ("cache", "Cache"),
                            ("queue", "Message Queue"),
                            ("storage", "Storage"),
                            ("external_service", "External Service"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("status_message", models.TextField(blank=True)),
                (
                    "response_time",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("dependencies", models.JSONField(blank=True, default=dict)),
                ("check_url", models.URLField(blank=True)),
                ("check_timeout", models.IntegerField(default=30)),
                ("check_interval", models.IntegerField(default=60)),
                ("alert_enabled", models.BooleanField(default=True)),
                ("alert_thresholds", models.JSONField(blank=True, default=dict)),
                ("last_alert_sent", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.IntegerField(default=0)),
                ("last_success", models.DateTimeField(blank=True, null=True)),
                ("last_failure", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("environment", models.CharField(default="production", max_length=50)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["component_type", "component_name"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "setting_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean"),
                            ("json", "JSON"),
                            ("choice", "Choice"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                ("value", models.TextField()),
                ("default_value", models.TextField(blank=True)),
                ("choices", models.JSONField(blank=True, default=list)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "required_role",
                    models.CharField(default="administrator", max_length=20),
                ),
                ("category", models.CharField(default="general", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("de", "German"),
                            ("zh", "Chinese"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("GHS", "Ghanaian Cedi"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                        ],
                        default="GHS",
                        max_length=10,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("DD/MM/YYYY", "DD/MM/YYYY"),
                            ("MM/DD/YYYY", "MM/DD/YYYY"),
                            ("YYYY-MM-DD", "YYYY-MM-DD"),
                        ],
                        default="DD/MM/YYYY",
                        max_length=15,
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        choices=[("12h", "12 Hour"), ("24h", "24 Hour")],
                        default="24h",
                        max_length=5,
                    ),
                ),
                ("dashboard_layout", models.JSONField(blank=True, default=dict)),
                (
                    "default_dashboard_view",
                    models.CharField(default="overview", max_length=50),
                ),
                ("items_per_page", models.IntegerField(default=25)),
                ("auto_refresh_interval", models.IntegerField(default=60)),
                (
                    "default_transaction_type",
                    models.CharField(default="deposit", max_length=20),
                ),
                ("require_transaction_confirmation", models.BooleanField(default=True)),
                ("show_transaction_receipts", models.BooleanField(default=True)),
                (
                    "transaction_notification_threshold",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1000.00"), max_digits=12
                    ),
                ),
                ("session_timeout", models.IntegerField(default=30)),
                ("require_2fa", models.BooleanField(default=False)),
                ("login_alerts", models.BooleanField(default=True)),
                ("suspicious_activity_alerts", models.BooleanField(default=True)),
                ("cash_drawer_shortcuts", models.BooleanField(default=True)),
                ("auto_calculate_change", models.BooleanField(default=True)),
                ("receipt_printer_enabled", models.BooleanField(default=False)),
                (
                    "receipt_printer_address",
                    models.CharField(blank=True, max_length=100),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("push_notifications", models.BooleanField(default=True)),
                ("notification_sound", models.BooleanField(default=True)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("high_contrast_mode", models.BooleanField(default=False)),
                ("large_text", models.BooleanField(default=False)),
                ("screen_reader_optimized", models.BooleanField(default=False)),
                ("keyboard_navigation", models.BooleanField(default=True)),
                ("advanced_mode", models.BooleanField(default=False)),
                ("debug_mode", models.BooleanField(default=False)),
                ("api_access_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
