# Generated by Django 4.2 on 2025-12-07 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("settings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_system_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="healthcheck",
            index=models.Index(
                fields=["component_type"], name="settings_he_compone_00652c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthcheck",
            index=models.Index(fields=["status"], name="settings_he_status_3a431d_idx"),
        ),
        migrations.AddIndex(
            model_name="healthcheck",
            index=models.Index(
                fields=["environment"], name="settings_he_environ_a28e8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthcheck",
            index=models.Index(
                fields=["-updated_at"], name="settings_he_updated_ce72d0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="healthcheck",
            unique_together={("component_name", "component_type", "environment")},
        ),
        migrations.AddField(
            model_name="apiusage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_usage",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apiratelimit",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_rate_limits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="usersettings",
            index=models.Index(fields=["user"], name="settings_us_user_id_b56c1e_idx"),
        ),
        migrations.AddIndex(
            model_name="usersettings",
            index=models.Index(fields=["theme"], name="settings_us_theme_b3f1cb_idx"),
        ),
        migrations.AddIndex(
            model_name="usersettings",
            index=models.Index(
                fields=["language"], name="settings_us_languag_c0e588_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemsettings",
            index=models.Index(fields=["key"], name="settings_sy_key_c67abc_idx"),
        ),
        migrations.AddIndex(
            model_name="systemsettings",
            index=models.Index(
                fields=["category"], name="settings_sy_categor_752d2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemsettings",
            index=models.Index(
                fields=["is_active"], name="settings_sy_is_acti_ce30a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusage",
            index=models.Index(
                fields=["user", "-timestamp"], name="settings_ap_user_id_380e39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusage",
            index=models.Index(
                fields=["endpoint", "-timestamp"], name="settings_ap_endpoin_0fba14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusage",
            index=models.Index(fields=["method"], name="settings_ap_method_ad5026_idx"),
        ),
        migrations.AddIndex(
            model_name="apiusage",
            index=models.Index(
                fields=["status_code"], name="settings_ap_status__e76e64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusage",
            index=models.Index(
                fields=["-timestamp"], name="settings_ap_timesta_d9459d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiratelimit",
            index=models.Index(fields=["scope"], name="settings_ap_scope_ce890c_idx"),
        ),
        migrations.AddIndex(
            model_name="apiratelimit",
            index=models.Index(
                fields=["is_active"], name="settings_ap_is_acti_b10fd0_idx"
            ),
        ),
    ]
