# Generated by Django 4.2 on 2025-12-10 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("settings", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique setting key", max_length=100, unique=True
                    ),
                ),
                ("value", models.TextField(help_text="Setting value (stored as text)")),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("boolean", "Boolean"),
                            ("json", "JSON"),
                            ("float", "Float"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of what this setting controls"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("security", "Security"),
                            ("transactions", "Transactions"),
                            ("notifications", "Notifications"),
                            ("performance", "Performance"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="system",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this setting is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
                "ordering": ["category", "key"],
            },
        ),
        migrations.RemoveField(
            model_name="apiratelimit",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="apiusage",
            name="user",
        ),
        migrations.DeleteModel(
            name="HealthCheck",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="user",
        ),
        migrations.DeleteModel(
            name="APIRateLimit",
        ),
        migrations.DeleteModel(
            name="APIUsage",
        ),
        migrations.DeleteModel(
            name="SystemSettings",
        ),
        migrations.DeleteModel(
            name="UserSettings",
        ),
        migrations.AddIndex(
            model_name="systemsetting",
            index=models.Index(fields=["key"], name="settings_sy_key_d49ddf_idx"),
        ),
        migrations.AddIndex(
            model_name="systemsetting",
            index=models.Index(
                fields=["category"], name="settings_sy_categor_7c2f34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemsetting",
            index=models.Index(
                fields=["is_active"], name="settings_sy_is_acti_56e390_idx"
            ),
        ),
    ]
