"""
Django settings for banking_backend project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import logging
from pathlib import Path
from decouple import config
import dj_database_url
import structlog
from django.core.exceptions import ImproperlyConfigured
# from django_structlog.middlewares import get_request_header  # Commented out due to import error

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-development-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ENVIRONMENT = config('ENVIRONMENT', default='development')

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'auditlog',
    'django_prometheus',
    'health_check',
    'health_check.db',
    'health_check.cache',
    'health_check.storage',
    'health_check.contrib.migrations',
    'django_structlog',
    'channels',
    'users',
    'authentication',
    'banking',
    'transactions',
    'operations',
    'reports',
    'fraud_detection',
    'chat',
    'products',
    'services',
    'performance',
    'settings',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # 'security.middleware.SecurityMiddleware',  # Commented out - module not found
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # Must be before auth middleware
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_structlog.middlewares.RequestMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = config('DATABASE_URL', default=f'sqlite:///{BASE_DIR}/db.sqlite3')
DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL)
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static files storage for production (WhiteNoise)
if ENVIRONMENT == 'production':
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    # Add WhiteNoise middleware after SecurityMiddleware
    MIDDLEWARE.insert(
        MIDDLEWARE.index('django.middleware.security.SecurityMiddleware') + 1,
        'whitenoise.middleware.WhiteNoiseMiddleware',
    )

# Cache configuration
import os
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Custom authentication backends
AUTHENTICATION_BACKENDS = [
    'authentication.backends.FrontendAuthBackend',  # Custom backend first for frontend
    'users.auth_backend.EmailAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',    # Default backend for admin
]

# Login URL for Django auth redirects
LOGIN_URL = '/users/web/login/'

# CORS settings
# Security: Only allow specific origins in production
if ENVIRONMENT == 'production':
    # In production,  # be very restrictive with CORS
    CORS_ALLOW_ALL_ORIGINS = False
    cors_origins = config('CORS_ALLOWED_ORIGINS', default='', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])
    # Strict HTTPS-only origins in production
    CORS_ALLOWED_ORIGINS = [origin for origin in cors_origins if origin.startswith('https://')]
    if not CORS_ALLOWED_ORIGINS:
        raise ImproperlyConfigured("CORS_ALLOWED_ORIGINS must be set to HTTPS origins in production")
    CORS_ALLOW_CREDENTIALS = config('CORS_ALLOW_CREDENTIALS', default=False, cast=bool)
else:
    # In development,  # allow localhost for testing
    CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=True, cast=bool)
    CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001,http://localhost:5173,http://127.0.0.1:5173', cast=lambda v: [s.strip() for s in v.split(',')])
    CORS_ALLOW_CREDENTIALS = True

# Additional CORS headers for preflight requests
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_PREFLIGHT_MAX_AGE = 86400  # 4 hours

# CSRF settings for cross-origin requests
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001', cast=lambda v: [s.strip() for s in v.split(',')])

# Email settings (for password reset)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@bankingapp.com')
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': config('ANON_RATE_LIMIT', default='100/hour'),
        'user': config('USER_RATE_LIMIT', default='1000/hour'),
    },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'banking_backend.utils.error_handling.custom_exception_handler',
    # Test settings
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'TEST_REQUEST_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# DRF Spectacular configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'Banking API',
    'DESCRIPTION': 'Comprehensive Banking API for managing accounts, transactions, loans, and operations',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': False,
    'TAGS': [
        {'name': 'Authentication', 'description': 'User authentication and authorization'},
        {'name': 'Banking', 'description': 'Core banking operations'},
        {'name': 'Transactions', 'description': 'Transaction management'},
        {'name': 'Operations', 'description': 'Administrative operations'},
        {'name': 'Users', 'description': 'User management'},
    ],
    'SECURITY': [
        {
            'Bearer': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    ],
    'SECURITY_REQUIREMENTS': [
        {
            'Bearer': []
        }
    ],
}

# Channels configuration
try:
    import channels_redis
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [config('REDIS_URL', default='redis://127.0.0.1:6379/0')],
            },
        },
    }
except ImportError:
    # Fallback to in-memory channel layer for development
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# Redis configuration for fraud detection system
REDIS_URL = config('REDIS_URL', default='redis://127.0.0.1:6379/0')
REDIS_HOST = config('REDIS_HOST', default='127.0.0.1')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)
REDIS_DB = config('REDIS_DB', default=0, cast=int)
REDIS_RULES_DB = config('REDIS_RULES_DB', default=1, cast=int)
REDIS_LOG_DB = config('REDIS_LOG_DB', default=2, cast=int)

# Fraud detection settings
FRAUD_SCORE_THRESHOLD = config('FRAUD_SCORE_THRESHOLD', default=60, cast=int)
FRAUD_AUDIT_ENCRYPTION_KEY = config('FRAUD_AUDIT_ENCRYPTION_KEY', default=None)
RULE_CACHE_TTL = config('RULE_CACHE_TTL', default=3600, cast=int)  # 1 hour
LOG_RETENTION_DAYS = config('LOG_RETENTION_DAYS', default=30, cast=int)

# JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=config('ACCESS_TOKEN_LIFETIME_MINUTES', default=60, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=config('REFRESH_TOKEN_LIFETIME_DAYS', default=1, cast=int)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Content Security Policy (CSP) settings for banking application
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com", "https://cdn.jsdelivr.net")
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com")
CSP_IMG_SRC = ("'self'", "data:", "https:")
CSP_CONNECT_SRC = ("'self'",)
CSP_FRAME_SRC = ("'none'",)
CSP_OBJECT_SRC = ("'none'",)
CSP_BASE_URI = ("'self'",)
CSP_FORM_ACTION = ("'self'",)
CSP_FRAME_ANCESTORS = ("'none'",)

# Additional security headers
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = 'require-corp'

# Environment-specific security configurations
if ENVIRONMENT == 'development':
    # Relaxed CSP for development
    CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'", "https://cdn.jsdelivr.net")
    CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com", "https://cdn.jsdelivr.net")
    CSP_CONNECT_SRC = ("'self'", "ws:", "wss:", "http://localhost:3000", "http://127.0.0.1:3000")
    # Disable strict COEP in development
    SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = None
elif ENVIRONMENT == 'production':
    # Strict CSP for production
    CSP_SCRIPT_SRC = ("'self'", "https://cdn.jsdelivr.net")
    CSP_STYLE_SRC = ("'self'", "https://fonts.googleapis.com", "https://cdn.jsdelivr.net")
    CSP_CONNECT_SRC = ("'self'",)
    SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = 'require-corp'

# HTTPS enforcement settings
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=ENVIRONMENT == 'production', cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=True, cast=bool)
SECURE_REDIRECT_EXEMPT = config('SECURE_REDIRECT_EXEMPT', default='', cast=lambda v: [s.strip() for s in v.split(',')] if v else [])
SECURE_SSL_HOST = config('SECURE_SSL_HOST', default=None)
SECURE_PROXY_SSL_HEADER = config('SECURE_PROXY_SSL_HEADER', default='', cast=lambda v: tuple(v.split(',')) if v else None)


# Encryption settings
ENCRYPTION_KEY = config('ENCRYPTION_KEY', default=None)
ENCRYPTION_SALT = config('ENCRYPTION_SALT', default=None)

# Enforce production encryption keys
if not ENCRYPTION_KEY or not ENCRYPTION_SALT:
    if ENVIRONMENT == 'production':
        raise ImproperlyConfigured(
            "ENCRYPTION_KEY and ENCRYPTION_SALT must be set in environment variables for production"
        )
    # For development,  # generate secure but temporary keys
    import secrets
    import base64
    ENCRYPTION_KEY = base64.urlsafe_b64encode(secrets.token_bytes(32)).decode()
    ENCRYPTION_SALT = base64.urlsafe_b64encode(secrets.token_bytes(16)).decode()

# Audit logging settings
AUDITLOG_INCLUDE_ALL_MODELS = config('AUDITLOG_INCLUDE_ALL_MODELS', default=True, cast=bool)
AUDITLOG_EXCLUDE_TRACKING_MODELS = config('AUDITLOG_EXCLUDE_TRACKING_MODELS', default='auditlog.LogEntry', cast=lambda v: tuple(v.split(',')))
AUDITLOG_DISABLE_REMOTE_ADDR = config('AUDITLOG_DISABLE_REMOTE_ADDR', default=False, cast=bool)

# Test settings
TEST_RUNNER = 'django.test.runner.DiscoverRunner'
TEST_OUTPUT_DIR = config('TEST_OUTPUT_DIR', default='test-results')
TEST_PARALLEL = config('TEST_PARALLEL', default=1, cast=int)

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json_formatter': {
            '()': structlog.stdlib.ProcessorFormatter,
            'processor': structlog.dev.ConsoleRenderer(colors=False),
        },
        'colored_console': {
            '()': structlog.stdlib.ProcessorFormatter,
            'processor': structlog.dev.ConsoleRenderer(colors=True),
        },
        'key_value': {
            '()': structlog.stdlib.ProcessorFormatter,
            'processor': structlog.processors.KeyValueRenderer(key_order=['timestamp', 'level', 'event', 'logger']),
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'colored_console',
        },
        'json_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'app.log'),
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'json_formatter',
        },
        'security_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'json_formatter',
        },
        'transaction_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'transactions.log'),
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'json_formatter',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],  # Removed json_file to avoid Windows file locking issues
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],  # Removed json_file to avoid Windows file locking issues
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],  # Removed security_file to avoid Windows file locking issues
            'level': 'WARNING',
            'propagate': False,
        },
        'banking_backend': {
            'handlers': ['console'],  # Removed json_file to avoid Windows file locking issues
            'level': 'INFO',
            'propagate': False,
        },
        'banking_backend.security': {
            'handlers': ['console'],  # Removed security_file to avoid Windows file locking issues
            'level': 'INFO',
            'propagate': False,
        },
        'banking_backend.transactions': {
            'handlers': ['console'],  # Removed transaction_file to avoid Windows file locking issues
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],  # Removed json_file to avoid Windows file locking issues
        'level': 'INFO',
    },
}

# Structlog configuration
structlog.configure(
    processors=[
        structlog.stdlib.filter_by_level,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.UnicodeDecoder(),
        structlog.processors.ExceptionPrettyPrinter(),
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    context_class=dict,
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)

# Sentry configuration with enhanced validation and health checks
def validate_sentry_dsn(dsn):
    """Validate Sentry DSN format and accessibility."""
    if not dsn:
        return False, "DSN is empty"

    # Basic format validation
    import re
    dsn_pattern = r'^https://[a-f0-9]+@(?:[a-zA-Z0-9-]+\.)*sentry\.io/[0-9]+$'
    if not re.match(dsn_pattern, dsn):
        return False, "Invalid DSN format"

    # Check for placeholder values
    if 'your-sentry-dsn-here' in dsn or 'project-id' in dsn:
        return False, "DSN contains placeholder values"

    return True, "Valid DSN"

def check_sentry_health():
    """Perform basic health check for Sentry configuration."""
    try:
        import sentry_sdk
        # Test Sentry by capturing a test message (won't be sent in development)
        with sentry_sdk.configure_scope() as scope:
            scope.set_tag('health_check', 'true')
            sentry_sdk.capture_message("Sentry health check", level="info")
        return True, "Sentry health check passed"
    except Exception as e:
        return False, f"Sentry health check failed: {str(e)}"

try:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_dsn = config('SENTRY_DSN', default=None)
    sentry_enabled = config('SENTRY_ENABLED', default=True, cast=bool)

    if sentry_enabled and sentry_dsn:
        # Validate DSN
        is_valid, validation_message = validate_sentry_dsn(sentry_dsn)
        if not is_valid:
            print(f"[WARNING] Sentry DSN validation failed: {validation_message}")
            print("[INFO] Continuing without Sentry configuration")
        else:
            # Initialize Sentry
            sentry_sdk.init(
                dsn=sentry_dsn,
                integrations=[DjangoIntegration()],
                traces_sample_rate=config('SENTRY_TRACES_SAMPLE_RATE', default=1.0, cast=float),
                send_default_pii=config('SENTRY_SEND_DEFAULT_PII', default=False, cast=bool),
                environment=config('ENVIRONMENT', default='development'),
                release=config('RELEASE_VERSION', default=None),
                # Additional configuration for better error tracking
                before_send=lambda event, hint: event if not getattr(hint, 'exc_info', None) or not any(
                    'KeyboardInterrupt' in str(arg) for arg in hint.exc_info
                ) else None,  # Filter out KeyboardInterrupt
                debug=config('SENTRY_DEBUG', default=False, cast=bool),
            )

            # Perform health check
            health_ok, health_message = check_sentry_health()
            if health_ok:
                print("[INFO] Sentry initialized successfully")
            else:
                print(f"[WARNING] {health_message}")
    else:
        print("[INFO] Sentry disabled or DSN not configured")

except ImportError as e:
    print(f"[WARNING] Sentry SDK not installed: {str(e)}")
    print("[INFO] Continuing without Sentry configuration")
except Exception as e:
    print(f"[ERROR] Sentry configuration failed: {str(e)}")
    print("[INFO] Continuing without Sentry configuration")

# Test database settings
import sys
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }
    # Use console email backend for tests
    EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
    # Disable audit logging in tests for performance
    AUDITLOG_INCLUDE_ALL_MODELS = False
    AUDITLOG_EXCLUDE_TRACKING_MODELS = ()
    # Use locmem cache for tests (acceptable for django-ratelimit)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }