# Generated by Django 4.2 on 2025-11-20 15:11

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_date', models.DateField(default=datetime.date.today)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('filters_applied', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('format', models.CharField(choices=[('json', 'JSON'), ('html', 'HTML'), ('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='json', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('transaction_summary', 'Transaction Summary'), ('cashier_activity', 'Cashier Activity Report'), ('compliance', 'Compliance Report'), ('financial_overview', 'Financial Overview'), ('custom', 'Custom Report')], max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('layout_config', models.JSONField(blank=True, default=dict)),
                ('filters_config', models.JSONField(blank=True, default=dict)),
                ('columns_config', models.JSONField(blank=True, default=dict)),
                ('charts_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('next_run', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('dashboard', 'Dashboard Only'), ('api', 'API Access'), ('file_system', 'File System')], default='dashboard', max_length=20)),
                ('delivery_config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('error', 'Error')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_error', models.TextField(blank=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_report_schedules', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='ReportAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('average_transaction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposits_count', models.PositiveIntegerField(default=0)),
                ('withdrawals_count', models.PositiveIntegerField(default=0)),
                ('transfers_count', models.PositiveIntegerField(default=0)),
                ('fees_count', models.PositiveIntegerField(default=0)),
                ('deposits_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('withdrawals_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('transfers_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('fees_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cashier_metrics', models.JSONField(blank=True, default=dict)),
                ('previous_period_comparison', models.JSONField(blank=True, default=dict)),
                ('trend_data', models.JSONField(blank=True, default=dict)),
                ('compliance_flags', models.JSONField(blank=True, default=dict)),
                ('risk_indicators', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='reports.report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.reporttemplate'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['template_type'], name='reports_rep_templat_46c2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['frequency'], name='reports_rep_frequen_d0a338_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['is_active'], name='reports_rep_is_acti_4b0ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['status'], name='reports_rep_status_86d39b_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['next_run'], name='reports_rep_next_ru_8865e3_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['frequency'], name='reports_rep_frequen_1e97ea_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['is_active'], name='reports_rep_is_acti_7832b3_idx'),
        ),
        migrations.AddIndex(
            model_name='reportanalytics',
            index=models.Index(fields=['calculated_at'], name='reports_rep_calcula_d16c55_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_rep_status_c732ef_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_date'], name='reports_rep_report__cd5337_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['template'], name='reports_rep_templat_31c9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_by'], name='reports_rep_generat_4dc4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['expires_at'], name='reports_rep_expires_6eb760_idx'),
        ),
    ]
