# Generated by Django 4.2 on 2025-12-07 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reporttemplate",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_report_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_report_schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="reports.reporttemplate",
            ),
        ),
        migrations.AddField(
            model_name="reportanalytics",
            name="report",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="reports.report",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="reports.reporttemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["template_type"], name="reports_rep_templat_46c2c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["frequency"], name="reports_rep_frequen_d0a338_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["is_active"], name="reports_rep_is_acti_4b0ce5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(fields=["status"], name="reports_rep_status_86d39b_idx"),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["next_run"], name="reports_rep_next_ru_8865e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["frequency"], name="reports_rep_frequen_1e97ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["is_active"], name="reports_rep_is_acti_7832b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportanalytics",
            index=models.Index(
                fields=["calculated_at"], name="reports_rep_calcula_d16c55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["status"], name="reports_rep_status_c732ef_idx"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_date"], name="reports_rep_report__cd5337_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["template"], name="reports_rep_templat_31c9f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["generated_by"], name="reports_rep_generat_4dc4d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["expires_at"], name="reports_rep_expires_6eb760_idx"
            ),
        ),
    ]
