# Generated by Django 5.1 on 2025-12-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_complaint_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('daily_susu', 'Daily Susu'), ('shares', 'Shares'), ('monthly_contribution', 'Monthly Contribution')], default='daily_susu', max_length=25),
        ),
    ]
