# Generated by Django 5.1 on 2025-12-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_account_opening_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountopeningrequest',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='accountopeningrequest',
            name='id_type',
            field=models.CharField(choices=[('ghana_card', 'Ghana Card'), ('voter_id', 'Voter ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('nhis_card', 'NHIS Card'), ('other', 'Other')], default='ghana_card', max_length=20),
        ),
    ]
