# Generated by Django 5.1 on 2025-12-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_id_fields_to_account_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountopeningrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
