# Generated by Django 5.1 on 2025-12-12 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_make_email_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClosureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closure_reason', models.CharField(choices=[('customer_request', 'Customer Request'), ('account_inactive', 'Account Inactive'), ('fraud_suspected', 'Fraud Suspected'), ('compliance', 'Compliance Issue'), ('other', 'Other')], max_length=30)),
                ('other_reason', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('otp_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('final_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_requests', to='core.account')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_account_closures', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_account_closures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Closure Request',
                'verbose_name_plural': 'Account Closure Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
