# Generated by Django 5.1 on 2025-12-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_message_reactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="auth_tag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="encrypted_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="iv",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(default="text", max_length=50),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
