# Generated by Django 5.1 on 2025-12-12 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_reporttemplate_systemhealth_cashadvance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessagePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_enabled', models.BooleanField(default=True)),
                ('notification_sound', models.CharField(choices=[('default', 'Default'), ('chime', 'Chime'), ('ding', 'Ding'), ('bell', 'Bell'), ('none', 'Silent')], default='default', max_length=50)),
                ('read_receipts_enabled', models.BooleanField(default=True)),
                ('typing_indicators_enabled', models.BooleanField(default=True)),
                ('last_seen_visible', models.BooleanField(default=True)),
                ('auto_delete_enabled', models.BooleanField(default=False)),
                ('auto_delete_days', models.IntegerField(choices=[(1, '24 Hours'), (7, '7 Days'), (30, '30 Days'), (90, '90 Days'), (365, 'Never')], default=30)),
                ('markdown_enabled', models.BooleanField(default=True)),
                ('emoji_shortcuts_enabled', models.BooleanField(default=True)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Message Preferences',
                'verbose_name_plural': 'User Message Preferences',
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked User',
                'verbose_name_plural': 'Blocked Users',
                'ordering': ['-created_at'],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
