# Generated by Django 5.1 on 2025-12-13 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_operationsmessage_visitschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Visit'), ('due_payment', 'Due Payment'), ('overdue_payment', 'Overdue Payment'), ('loan_application', 'Loan Application'), ('account_opening', 'Account Opening'), ('follow_up', 'Follow Up'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('next_visit', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_bankers', to=settings.AUTH_USER_MODEL)),
                ('mobile_banker', models.ForeignKey(limit_choices_to={'role': 'mobile_banker'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Assignment',
                'verbose_name_plural': 'Client Assignments',
                'ordering': ['-priority', 'next_visit'],
                'unique_together': {('mobile_banker', 'client')},
            },
        ),
    ]
