# Generated by Django 5.1 on 2025-12-27 05:45
# Modified to be idempotent - checks if tables exist before creating

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def add_initial_balance_if_not_exists(apps, schema_editor):
    """Add initial_balance column to account if it doesn't exist."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name FROM information_schema.columns
                WHERE table_name = 'core_account' AND column_name = 'initial_balance'
            """)
            if cursor.fetchone():
                return
        elif connection.vendor == 'sqlite':
            cursor.execute("PRAGMA table_info(core_account)")
            columns = [column[1] for column in cursor.fetchall()]
            if 'initial_balance' in columns:
                return
        else:
            # Fallback for other vendors or unexpected state
            return

        cursor.execute("""
            ALTER TABLE core_account
            ADD COLUMN initial_balance NUMERIC(15, 2) NOT NULL DEFAULT 0.00
        """)


def noop(apps, schema_editor):
    """No-op for reverse migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remove_old_messaging"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Make initial balance idempotent
        migrations.RunPython(add_initial_balance_if_not_exists, reverse_code=noop),
    ]
