# Generated by Django 5.1 on 2025-12-27 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_add_initial_balance_and_quantize"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="checkdeposit",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who initiated this check deposit",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_check_deposits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
