# Generated by Django 5.1 on 2026-01-06 09:08
# Modified to be idempotent - checks if column exists before adding

from decimal import Decimal
from django.db import migrations, models


def add_initial_deposit_if_not_exists(apps, schema_editor):
    """Add initial_deposit column only if it doesn't already exist."""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if column already exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'core_accountopeningrequest' 
            AND column_name = 'initial_deposit'
        """)
        if cursor.fetchone():
            # Column already exists, skip
            return
    
    # Column doesn't exist, add it using schema_editor
    AccountOpeningRequest = apps.get_model('core', 'AccountOpeningRequest')
    field = models.DecimalField(
        decimal_places=2,
        default=Decimal("0.00"),
        max_digits=15,
    )
    field.set_attributes_from_name('initial_deposit')
    
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE core_accountopeningrequest 
            ADD COLUMN initial_deposit NUMERIC(15, 2) DEFAULT 0.00 NOT NULL
        """)


def reverse_migration(apps, schema_editor):
    """Remove the column if it exists."""
    from django.db import connection
    
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'core_accountopeningrequest' 
            AND column_name = 'initial_deposit'
        """)
        if cursor.fetchone():
            cursor.execute("""
                ALTER TABLE core_accountopeningrequest 
                DROP COLUMN initial_deposit
            """)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_add_maker_checker_fields"),
    ]

    operations = [
        migrations.RunPython(
            add_initial_deposit_if_not_exists,
            reverse_code=reverse_migration,
        ),
    ]
