# Generated by Django 5.1 on 2026-01-06 09:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_add_maker_checker_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountopeningrequest",
            name="initial_deposit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Initial deposit amount (optional, can be 0)",
                max_digits=15,
            ),
        ),
    ]
