# Generated by Django 5.1 on 2026-01-06 09:08
# Modified to be idempotent - checks if column exists before adding

from decimal import Decimal
from django.db import migrations, models


def add_initial_deposit_if_not_exists(apps, schema_editor):
    """Add initial_deposit column only if it doesn't already exist."""
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name = 'core_accountopeningrequest'
                AND column_name = 'initial_deposit'
            """)
            if cursor.fetchone():
                return
        elif connection.vendor == 'sqlite':
            cursor.execute("PRAGMA table_info(core_accountopeningrequest)")
            columns = [column[1] for column in cursor.fetchall()]
            if 'initial_deposit' in columns:
                return
        else:
            return

    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute("""
                ALTER TABLE core_accountopeningrequest
                ADD COLUMN initial_deposit NUMERIC(15, 2) DEFAULT 0.00 NOT NULL
            """)
        else:
            cursor.execute("""
                ALTER TABLE core_accountopeningrequest
                ADD COLUMN initial_deposit NUMERIC(15, 2) DEFAULT 0.00
            """)


def reverse_migration(apps, schema_editor):
    """Remove the column if it exists."""
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name = 'core_accountopeningrequest'
                AND column_name = 'initial_deposit'
            """)
            if not cursor.fetchone():
                return
        elif connection.vendor == 'sqlite':
            cursor.execute("PRAGMA table_info(core_accountopeningrequest)")
            columns = [column[1] for column in cursor.fetchall()]
            if 'initial_deposit' not in columns:
                return
        else:
            return
            if connection.vendor == 'postgresql':
                cursor.execute("""
                    ALTER TABLE core_accountopeningrequest
                    DROP COLUMN initial_deposit
                """)
            else:
                # SQLite doesn't support DROP COLUMN easily, but we can skip it or use Django's schema_editor
                # Since this is a manual idempotent migration, we'll just skip to avoid complex SQLite logic
                pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_add_maker_checker_fields"),
    ]

    operations = [
        migrations.RunPython(
            add_initial_deposit_if_not_exists,
            reverse_code=reverse_migration,
        ),
    ]
