# Generated by Django 5.1 on 2026-01-12 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_add_initial_deposit_to_account_opening"),
    ]

    operations = [
        migrations.AddField(
            model_name="fraudalert",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fraud_alerts",
                to="core.transaction",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="purpose",
            field=models.TextField(
                blank=True, help_text="Purpose of the loan", null=True
            ),
        ),
    ]
