# Generated by Django 5.1 on 2026-01-13 05:31
# Fixed: Removed duplicate fields (initial_balance from 0020, initial_deposit from 0022)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_audit_fixes"),
    ]

    operations = [
        # NOTE: Removed duplicate AddField operations:
        # - initial_balance (already added in migration 0020)
        # - initial_deposit (already added in migration 0022)
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("daily_susu", "Daily Savings"),
                    ("member_savings", "Member Savings"),
                    ("youth_savings", "Youth Savings"),
                    ("shares", "Shares"),
                ],
                default="daily_susu",
                max_length=25,
            ),
        ),
    ]
