# Generated by Django 5.1 on 2026-01-13 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_audit_fixes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cashadvance",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who created this cash advance request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_cash_advances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
