# Generated by Django 5.1 on 2026-01-13 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_add_submitted_by_to_cash_advance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accountopeningrequest",
            name="credentials_approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Manager who approved the dispatch of login credentials",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credential_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="credentials_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
