# Generated by Django 5.1 on 2026-01-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_production_readiness_standardization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operationsmessage",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="visitschedule",
            options={"ordering": ["-scheduled_time"]},
        ),
        migrations.AlterModelTable(
            name="clientassignment",
            table="client_assignment",
        ),
        migrations.AlterModelTable(
            name="operationsmessage",
            table="operations_message",
        ),
        migrations.AlterModelTable(
            name="visitschedule",
            table="visit_schedule",
        ),
    ]
