# Generated by Django 5.1 on 2026-01-14 10:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_operationsmessage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="loan",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="digital_address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="loan",
            name="employment_status",
            field=models.CharField(default="employed", max_length=50),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_1_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_1_id_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_1_id_type",
            field=models.CharField(default="ghana_card", max_length=50),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_1_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_1_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_2_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_2_id_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_2_id_type",
            field=models.CharField(default="ghana_card", max_length=50),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_2_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_2_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="loan",
            name="id_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="loan",
            name="id_type",
            field=models.CharField(default="ghana_card", max_length=50),
        ),
        migrations.AddField(
            model_name="loan",
            name="monthly_income",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="next_of_kin_1_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="next_of_kin_1_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="loan",
            name="next_of_kin_1_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="loan",
            name="next_of_kin_1_relationship",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="loan",
            name="next_of_kin_2_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="next_of_kin_2_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="loan",
            name="next_of_kin_2_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="loan",
            name="next_of_kin_2_relationship",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="loan",
            name="town",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
