# Generated by Django 5.1 on 2026-01-14 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_loan_city_loan_date_of_birth_loan_digital_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("transfer", "Transfer"),
                    ("payment", "Payment"),
                    ("repayment", "Loan Repayment"),
                    ("fee", "Fee"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ClientRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_id", models.CharField(max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("ghana_card", "Ghana Card"),
                            ("voters_id", "Voter's ID"),
                            ("passport", "Passport"),
                            ("drivers_license", "Driver's License"),
                        ],
                        default="ghana_card",
                        max_length=20,
                    ),
                ),
                ("id_number", models.CharField(blank=True, max_length=50)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("daily_susu", "Daily Savings"),
                            ("member_savings", "Member Savings"),
                            ("youth_savings", "Youth Savings"),
                            ("shares", "Shares"),
                        ],
                        default="daily_susu",
                        max_length=25,
                    ),
                ),
                ("digital_address", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_verification", "Pending Verification"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_verification",
                        max_length=25,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registration_record",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Registration",
                "verbose_name_plural": "Client Registrations",
                "db_table": "client_registration",
                "ordering": ["-created_at"],
            },
        ),
    ]
