# Generated by Django 5.1 on 2026-01-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_add_client_registration_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountopeningrequest",
            name="digital_address",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="next_of_kin_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="occupation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="position",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="work_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="id_document",
            field=models.FileField(
                blank=True, null=True, upload_to="registration/ids/"
            ),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="next_of_kin_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="occupation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="passport_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="registration/passports/"
            ),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="position",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="work_address",
            field=models.TextField(blank=True),
        ),
    ]
