# Generated by Django 5.1 on 2026-01-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_accountopeningrequest_digital_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FraudRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("transaction_amount", "Transaction Amount"),
                            ("velocity", "Velocity"),
                            ("geographic", "Geographic"),
                            ("time_based", "Time Based"),
                            ("account_activity", "Account Activity"),
                        ],
                        default="transaction_amount",
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        help_text="Transaction field to evaluate", max_length=50
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        help_text="Comparison operator (e.g., >, <, ==)", max_length=20
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Threshold value for the rule", max_length=255
                    ),
                ),
                ("additional_conditions", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_block", models.BooleanField(default=False)),
                ("require_approval", models.BooleanField(default=False)),
                ("escalation_threshold", models.PositiveIntegerField(default=0)),
                ("trigger_count", models.PositiveIntegerField(default=0)),
                ("false_positive_count", models.PositiveIntegerField(default=0)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fraud Rule",
                "verbose_name_plural": "Fraud Rules",
                "ordering": ["-created_at"],
            },
        ),
    ]
