# Generated by Django 5.1.15 on 2026-02-04 11:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_fraudrule"),
    ]

    operations = [
        # NOTE: This migration is now a no-op because both fields were already added:
        # - initial_balance was added in migration 0020
        # - initial_deposit was added in migration 0022
    ]
