# Generated by Django 5.1.15 on 2026-02-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_encrypt_existing_accountopening_pii"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountopeningrequest",
            name="id_number_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="phone_number_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
    ]
