# Generated by Django 5.1.15 on 2026-02-04 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_accountopeningrequest_id_number_encrypted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usermessagepreference",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usermessagepreference",
            name="push_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usermessagepreference",
            name="show_previews",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="checkdeposit",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_check_deposits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["user", "-created_at"], name="account_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["account_type", "is_active"], name="account_type_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["is_active", "-balance"], name="account_active_balance_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountopeningrequest",
            index=models.Index(
                fields=["status", "-created_at"], name="acc_open_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountopeningrequest",
            index=models.Index(
                fields=["submitted_by", "-created_at"], name="acc_open_sub_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudalert",
            index=models.Index(fields=["user", "-created_at"], name="fraud_user_idx"),
        ),
        migrations.AddIndex(
            model_name="fraudalert",
            index=models.Index(
                fields=["severity", "is_resolved"], name="fraud_sev_res_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["user", "-created_at"], name="loan_user_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["status", "-created_at"], name="loan_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["from_account", "-timestamp"], name="tx_from_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["to_account", "-timestamp"], name="tx_to_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["status", "-timestamp"], name="tx_status_idx"),
        ),
        migrations.AlterModelTable(
            name="account",
            table="core_account",
        ),
        migrations.AlterModelTable(
            name="accountclosurerequest",
            table="core_accountclosurerequest",
        ),
        migrations.AlterModelTable(
            name="accountopeningrequest",
            table="core_accountopeningrequest",
        ),
        migrations.AlterModelTable(
            name="accountstatement",
            table="core_accountstatement",
        ),
        migrations.AlterModelTable(
            name="bankingmessage",
            table="core_bankingmessage",
        ),
        migrations.AlterModelTable(
            name="blockeduser",
            table="core_blockeduser",
        ),
        migrations.AlterModelTable(
            name="cashadvance",
            table="core_cashadvance",
        ),
        migrations.AlterModelTable(
            name="cashdrawer",
            table="core_cashdrawer",
        ),
        migrations.AlterModelTable(
            name="cashdrawerdenomination",
            table="core_cashdrawerdenomination",
        ),
        migrations.AlterModelTable(
            name="chatmessage",
            table="core_chatmessage",
        ),
        migrations.AlterModelTable(
            name="chatroom",
            table="core_chatroom",
        ),
        migrations.AlterModelTable(
            name="checkdeposit",
            table="core_checkdeposit",
        ),
        migrations.AlterModelTable(
            name="complaint",
            table="core_complaint",
        ),
        migrations.AlterModelTable(
            name="device",
            table="core_device",
        ),
        migrations.AlterModelTable(
            name="expense",
            table="core_expense",
        ),
        migrations.AlterModelTable(
            name="fraudalert",
            table="core_fraudalert",
        ),
        migrations.AlterModelTable(
            name="fraudrule",
            table="core_fraudrule",
        ),
        migrations.AlterModelTable(
            name="loan",
            table="core_loan",
        ),
        migrations.AlterModelTable(
            name="message",
            table="core_message",
        ),
        migrations.AlterModelTable(
            name="messagethread",
            table="core_messagethread",
        ),
        migrations.AlterModelTable(
            name="payslip",
            table="core_payslip",
        ),
        migrations.AlterModelTable(
            name="performancemetric",
            table="core_performancemetric",
        ),
        migrations.AlterModelTable(
            name="product",
            table="core_product",
        ),
        migrations.AlterModelTable(
            name="promotion",
            table="core_promotion",
        ),
        migrations.AlterModelTable(
            name="refund",
            table="core_refund",
        ),
        migrations.AlterModelTable(
            name="report",
            table="core_report",
        ),
        migrations.AlterModelTable(
            name="reportschedule",
            table="core_reportschedule",
        ),
        migrations.AlterModelTable(
            name="reporttemplate",
            table="core_reporttemplate",
        ),
        migrations.AlterModelTable(
            name="servicecharge",
            table="core_servicecharge",
        ),
        migrations.AlterModelTable(
            name="servicerequest",
            table="core_servicerequest",
        ),
        migrations.AlterModelTable(
            name="systemhealth",
            table="core_systemhealth",
        ),
        migrations.AlterModelTable(
            name="transaction",
            table="core_transaction",
        ),
    ]
