# Generated by Django 5.1.15 on 2026-02-04 21:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_usermessagepreference_email_notifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="initial_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="initial_deposit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Initial deposit amount (optional, can be 0)",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="accountopeningrequest",
            name="email",
            field=models.EmailField(
                default="",
                help_text="Customer email for login credentials",
                max_length=254,
            ),
        ),
    ]
