# Generated by Django 5.1.15 on 2026-02-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_usermessagepreference_email_notifications_and_more"),
    ]

    operations = [
        # NOTE: initial_balance and initial_deposit were already added in earlier migrations
        migrations.AlterField(
            model_name="accountopeningrequest",
            name="email",
            field=models.EmailField(
                default="",
                help_text="Customer email for login credentials",
                max_length=254,
            ),
        ),
    ]
