# Generated by Django 5.1.15 on 2026-02-06 04:07
# FIXED: Removed duplicate AddField operations for initial_balance (already in 0020)
# and initial_deposit (already in 0022) that caused CI failures.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_require_customer_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountopeningrequest",
            name="id_number",
        ),
        migrations.RemoveField(
            model_name="accountopeningrequest",
            name="phone_number",
        ),
        # NOTE: initial_balance was added in 0020_add_initial_balance_and_quantize.py
        # NOTE: initial_deposit was added in 0022_add_initial_deposit_to_account_opening.py
    ]
