# Generated by Django 5.1.15 on 2026-02-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_transaction_approval_date_transaction_approved_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientregistration",
            name="id_number",
        ),
        migrations.RemoveField(
            model_name="clientregistration",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="id_number_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="phone_number_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="id_number_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="id_number_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="phone_number_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="phone_number_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
