# Generated by Django 5.1 on 2026-02-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_remove_smsoutbox_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountclosurerequest",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="accountopeningrequest",
            name="address",
        ),
        migrations.RemoveField(
            model_name="accountopeningrequest",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="accountopeningrequest",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="accountopeningrequest",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="accountopeningrequest",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="accountopeningrequest",
            name="next_of_kin_data",
        ),
        migrations.AddField(
            model_name="accountclosurerequest",
            name="phone_number_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="address_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="date_of_birth_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="first_name_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="last_name_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="next_of_kin_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
    ]
