# Generated by Django 5.1.15 on 2026-02-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_remove_accountclosurerequest_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountopeningrequest",
            name="digital_address",
        ),
        migrations.RemoveField(
            model_name="accountopeningrequest",
            name="location",
        ),
        migrations.RemoveField(
            model_name="accountopeningrequest",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="accountopeningrequest",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="accountopeningrequest",
            name="position",
        ),
        migrations.RemoveField(
            model_name="accountopeningrequest",
            name="work_address",
        ),
        migrations.RemoveField(
            model_name="clientassignment",
            name="client_name",
        ),
        migrations.RemoveField(
            model_name="clientassignment",
            name="location",
        ),
        migrations.RemoveField(
            model_name="clientregistration",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="clientregistration",
            name="digital_address",
        ),
        migrations.RemoveField(
            model_name="clientregistration",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="clientregistration",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="clientregistration",
            name="location",
        ),
        migrations.RemoveField(
            model_name="clientregistration",
            name="next_of_kin_data",
        ),
        migrations.RemoveField(
            model_name="clientregistration",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="clientregistration",
            name="position",
        ),
        migrations.RemoveField(
            model_name="clientregistration",
            name="work_address",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="digital_address",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="guarantor_1_address",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="guarantor_1_id_number",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="guarantor_1_name",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="guarantor_1_phone",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="guarantor_2_address",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="guarantor_2_id_number",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="guarantor_2_name",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="guarantor_2_phone",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="id_number",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="next_of_kin_1_address",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="next_of_kin_1_name",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="next_of_kin_1_phone",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="next_of_kin_2_address",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="next_of_kin_2_name",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="next_of_kin_2_phone",
        ),
        migrations.RemoveField(
            model_name="visitschedule",
            name="client_name",
        ),
        migrations.RemoveField(
            model_name="visitschedule",
            name="location",
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="digital_address_encrypted_val",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="location_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="occupation_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="photo_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted Base64 encoded photo", null=True
            ),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="position_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="work_address_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="clientassignment",
            name="client_name_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="clientassignment",
            name="location_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="date_of_birth_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="digital_address_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="first_name_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="last_name_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="location_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="next_of_kin_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="occupation_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="position_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="clientregistration",
            name="work_address_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loan",
            name="date_of_birth_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loan",
            name="digital_address_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_1_address_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_1_id_number_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_1_id_number_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_1_name_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_1_phone_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_2_address_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_2_id_number_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_2_id_number_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_2_name_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_2_phone_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loan",
            name="id_number_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loan",
            name="id_number_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="next_of_kin_1_address_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loan",
            name="next_of_kin_1_name_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loan",
            name="next_of_kin_1_phone_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loan",
            name="next_of_kin_2_address_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loan",
            name="next_of_kin_2_name_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="loan",
            name="next_of_kin_2_phone_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="visitschedule",
            name="client_name_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="visitschedule",
            name="location_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
    ]
