# Generated by Django 5.1.15 on 2026-02-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_remove_accountopeningrequest_digital_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankingmessage",
            name="body",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="content",
        ),
        migrations.RemoveField(
            model_name="operationsmessage",
            name="message",
        ),
        migrations.AddField(
            model_name="bankingmessage",
            name="body_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="content_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="operationsmessage",
            name="message_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
    ]
