# Generated by Django 5.1.15
# Reconciles schema for initial_balance (Account) and initial_deposit (AccountOpeningRequest)
# using SeparateDatabaseAndState to ensure both the physical DB and Django state are in sync.

from decimal import Decimal
from django.db import migrations, models


def add_columns_safely(apps, schema_editor):
    """Add columns only if they don't exist, using vendor-safe checks."""
    connection = schema_editor.connection
    
    # Account.initial_balance
    with connection.cursor() as cursor:
        column_exists = False
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT 1 FROM information_schema.columns 
                WHERE table_name='core_account' AND column_name='initial_balance'
            """)
            column_exists = bool(cursor.fetchone())
        elif connection.vendor == 'sqlite':
            cursor.execute("PRAGMA table_info(core_account)")
            column_exists = any(row[1] == 'initial_balance' for row in cursor.fetchall())
            
        if not column_exists:
            with schema_editor.connection.schema_editor() as editor:
                # We can't easily use editor.add_field here without a model instance from apps
                # but we can use raw SQL that is simpler
                if connection.vendor == 'postgresql':
                    cursor.execute("ALTER TABLE core_account ADD COLUMN initial_balance NUMERIC(15, 2) DEFAULT 0.00 NOT NULL")
                else:
                    cursor.execute("ALTER TABLE core_account ADD COLUMN initial_balance NUMERIC(15, 2) DEFAULT 0.00")

    # AccountOpeningRequest.initial_deposit
    with connection.cursor() as cursor:
        column_exists = False
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT 1 FROM information_schema.columns 
                WHERE table_name='core_accountopeningrequest' AND column_name='initial_deposit'
            """)
            column_exists = bool(cursor.fetchone())
        elif connection.vendor == 'sqlite':
            cursor.execute("PRAGMA table_info(core_accountopeningrequest)")
            column_exists = any(row[1] == 'initial_deposit' for row in cursor.fetchall())
            
        if not column_exists:
            if connection.vendor == 'postgresql':
                cursor.execute("ALTER TABLE core_accountopeningrequest ADD COLUMN initial_deposit NUMERIC(15, 2) DEFAULT 0.00 NOT NULL")
            else:
                cursor.execute("ALTER TABLE core_accountopeningrequest ADD COLUMN initial_deposit NUMERIC(15, 2) DEFAULT 0.00")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_remove_bankingmessage_body_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="account",
                    name="initial_balance",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="The balance with which the account was opened",
                        max_digits=15,
                    ),
                ),
                migrations.AddField(
                    model_name="accountopeningrequest",
                    name="initial_deposit",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Initial deposit amount (optional, can be 0)",
                        max_digits=15,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_columns_safely, migrations.RunPython.noop),
            ],
        ),
    ]
