# Generated by Django 5.1.15 on 2026-03-26 10:15
# Refactored: Removed redundant AddField operations already covered by idempotent migrations 0020 and 0022.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_remove_bankingmessage_body_and_more"),
    ]

    operations = [
        # Redundant fields removed to resolve CI/CD migration conflicts
    ]
