# Generated by Django 5.1.15 on 2026-03-26 10:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_remove_bankingmessage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="initial_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="initial_deposit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Initial deposit amount (optional, can be 0)",
                max_digits=15,
            ),
        ),
    ]
