# Generated by Django 5.1.15 on 2026-03-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_account_initial_balance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smsoutbox",
            name="message",
        ),
        migrations.AddField(
            model_name="smsoutbox",
            name="message_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
    ]
