# Generated by Django 5.1.15 on 2026-03-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_security_encrypt_sms_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientassignment",
            name="client_name_encrypted",
        ),
    ]
