# Generated by Django 6.0.3 on 2026-03-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_fix_remove_client_assignment_duplicate_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="fraudalert",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="low",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="risk_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
