# Generated by Django 6.0.3 on 2026-04-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_alter_clientregistration_submitted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitschedule",
            name="check_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visitschedule",
            name="check_in_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="visitschedule",
            name="check_in_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
