# Generated by Django 6.0.3 on 2026-04-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_visitschedule_check_in_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payslip",
            name="month",
            field=models.IntegerField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ]
            ),
        ),
    ]
