# Generated by Django 6.0.3 on 2026-04-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alter_payslip_month"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for the sequence (e.g., 'staff_id')",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("last_value", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Global Sequence",
                "verbose_name_plural": "Global Sequences",
                "db_table": "global_sequence",
            },
        ),
    ]
