# Generated by Django 6.0.3 on 2026-04-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_globalsequence"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="account",
            table="account",
        ),
        migrations.AlterModelTable(
            name="accountclosurerequest",
            table="account_closure_request",
        ),
        migrations.AlterModelTable(
            name="accountopeningrequest",
            table="account_opening_request",
        ),
        migrations.AlterModelTable(
            name="accountstatement",
            table="account_statement",
        ),
        migrations.AlterModelTable(
            name="cashadvance",
            table="cash_advance",
        ),
        migrations.AlterModelTable(
            name="cashdrawer",
            table="cash_drawer",
        ),
        migrations.AlterModelTable(
            name="cashdrawerdenomination",
            table="cash_drawer_denomination",
        ),
        migrations.AlterModelTable(
            name="checkdeposit",
            table="check_deposit",
        ),
        migrations.AlterModelTable(
            name="complaint",
            table="complaint",
        ),
        migrations.AlterModelTable(
            name="device",
            table="device",
        ),
        migrations.AlterModelTable(
            name="loan",
            table="loan",
        ),
        migrations.AlterModelTable(
            name="refund",
            table="refund",
        ),
        migrations.AlterModelTable(
            name="servicecharge",
            table="service_charge",
        ),
        migrations.AlterModelTable(
            name="servicerequest",
            table="service_request",
        ),
        migrations.AlterModelTable(
            name="transaction",
            table="transaction",
        ),
        migrations.DeleteModel(
            name="ClientRegistration",
        ),
    ]
