# Generated by Django 6.0.3 on 2026-04-05 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_transaction_processed_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accountclosurerequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_account_closures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accountclosurerequest",
            name="is_flagged_for_review",
            field=models.BooleanField(
                default=False, help_text="Flagged for manager intervention."
            ),
        ),
        migrations.AddField(
            model_name="accountclosurerequest",
            name="is_stale",
            field=models.BooleanField(
                default=False,
                help_text="Closure request has exceeded the 24-hour window.",
            ),
        ),
        migrations.AddField(
            model_name="accountclosurerequest",
            name="key_version",
            field=models.IntegerField(
                default=1, help_text="The version of the encryption key used for PII."
            ),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_account_openings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="is_flagged_for_review",
            field=models.BooleanField(
                default=False, help_text="Flagged for manager intervention."
            ),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="is_stale",
            field=models.BooleanField(
                default=False, help_text="Request has exceeded the 24-hour window."
            ),
        ),
        migrations.AddField(
            model_name="accountopeningrequest",
            name="key_version",
            field=models.IntegerField(
                default=1, help_text="The version of the encryption key used for PII."
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="is_flagged_for_review",
            field=models.BooleanField(
                default=False, help_text="Flagged for manager intervention."
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="is_stale",
            field=models.BooleanField(
                default=False,
                help_text="Loan application has exceeded the 24-hour window.",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="key_version",
            field=models.IntegerField(
                default=1, help_text="The version of the encryption key used for PII."
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_flagged_for_review",
            field=models.BooleanField(
                default=False,
                help_text="Manually or automatically flagged for manager intervention.",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_stale",
            field=models.BooleanField(
                default=False,
                help_text="Transaction has exceeded the 24-hour approval window.",
            ),
        ),
        migrations.AddIndex(
            model_name="accountclosurerequest",
            index=models.Index(fields=["is_stale"], name="acc_close_stale_idx"),
        ),
        migrations.AddIndex(
            model_name="accountopeningrequest",
            index=models.Index(fields=["is_stale"], name="acc_open_stale_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["is_stale"], name="loan_stale_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["is_stale"], name="tx_stale_idx"),
        ),
    ]
