# Generated by Django 5.1.15 on 2026-04-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_accountclosurerequest_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Pending Approval"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("reversed", "Reversed"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
    ]
