# Generated by Django 5.1.15 on 2026-04-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_alter_transaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("transfer", "Transfer"),
                    ("payment", "Payment"),
                    ("repayment", "Loan Repayment"),
                    ("fee", "Fee"),
                    ("disbursement", "Loan Disbursement"),
                ],
                max_length=20,
            ),
        ),
    ]
