# Generated by Django 5.1.15 on 2026-04-07 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_alter_transaction_transaction_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who initiated the loan for the customer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiated_loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who initiated the refund request for the customer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiated_refunds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
