# Generated by Django 5.1.15 on 2026-04-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_product_approved_by_product_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashadvance",
            name="id_number_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="cashadvance",
            name="id_number_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="cashadvance",
            name="id_type",
            field=models.CharField(default="ghana_card", max_length=50),
        ),
        migrations.AddField(
            model_name="cashadvance",
            name="verification_notes",
            field=models.TextField(
                blank=True, help_text="Notes from physical ID verification"
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="id_number_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="refund",
            name="id_number_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="id_type",
            field=models.CharField(default="ghana_card", max_length=50),
        ),
        migrations.AddField(
            model_name="refund",
            name="verification_notes",
            field=models.TextField(
                blank=True, help_text="Notes from physical ID verification"
            ),
        ),
    ]
