# Generated by Django 5.1.15 on 2026-04-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_cashadvance_id_number_encrypted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="verification_notes",
            field=models.TextField(
                blank=True, help_text="Notes from physical ID and address verification"
            ),
        ),
    ]
