# Generated by Django 6.0.3 on 2026-04-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_accountopeningrequest_existing_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountopeningrequest",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("daily_susu", "Daily Susu"),
                    ("shares", "Shares"),
                    ("monthly_contribution", "Monthly Contribution"),
                    ("youth_savings", "Youth Savings"),
                ],
                default="daily_susu",
                max_length=25,
            ),
        ),
    ]
