# Generated by Django 5.1.15 on 2026-04-14 08:58

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_alter_accountopeningrequest_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="initial_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
