# Generated by Django 6.0.3 on 2026-04-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_alter_account_initial_balance_alter_expense_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="attachment_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="attachment_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="reactions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
