# Generated by Django 5.1.15 on 2026-04-15 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_chatmessage_attachment_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="read_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have read this message",
                related_name="read_chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
