# Generated by Django 5.1.15 on 2026-04-15 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_chatmessage_read_at_chatmessage_read_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent message for threaded replies",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="core.chatmessage",
            ),
        ),
    ]
