# Generated by Django 5.1.15 on 2026-06-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_chatmessage_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountopeningrequest",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("G", "Group")],
                default="",
                help_text="Demographic classification for CUA Financial & Statistical reporting.",
                max_length=1,
            ),
        ),
    ]
