# Generated by Django 5.1.15 on 2026-04-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_chatmessage_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("security", "Security Incident"),
                            ("performance", "Performance Degradation"),
                            ("reliability", "Infrastructure Failure"),
                        ],
                        default="security",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "system_alert",
                "ordering": ["-created_at"],
            },
        ),
    ]
