# Generated by Django 5.1.15 on 2026-06-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_add_gender_to_account_opening_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporttemplate",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("transaction", "Transaction Report"),
                    ("account", "Account Report"),
                    ("loan", "Loan Report"),
                    ("cash_advance", "Cash Advance Report"),
                    ("fraud", "Fraud Report"),
                    ("compliance", "Compliance Report"),
                    ("financial", "Financial Report"),
                    ("audit", "Audit Report"),
                    ("performance", "Performance Report"),
                ],
                max_length=20,
            ),
        ),
    ]
