# Generated by Django 4.2 on 2025-12-07 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=30)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("customer", "Customer/User"),
                            ("cashier", "Cashier"),
                            ("mobile_banker", "Mobile Banker"),
                            ("manager", "Manager"),
                            ("operations_manager", "Operations Manager"),
                            ("administrator", "Administrator"),
                            ("superuser", "Superuser"),
                        ],
                        default="customer",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "reset_token",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("reset_token_created_at", models.DateTimeField(blank=True, null=True)),
                ("failed_login_attempts", models.IntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("last_failed_login", models.DateTimeField(blank=True, null=True)),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "device_fingerprint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("two_factor_enabled", models.BooleanField(default=False)),
                (
                    "two_factor_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("failed_login", "Failed Login"),
                            ("password_change", "Password Change"),
                            ("password_reset", "Password Reset"),
                            ("user_created", "User Created"),
                            ("user_updated", "User Updated"),
                            ("user_deleted", "User Deleted"),
                            ("user_activated", "User Activated"),
                            ("user_deactivated", "User Deactivated"),
                            ("role_changed", "Role Changed"),
                            ("permission_denied", "Permission Denied"),
                            ("transaction_created", "Transaction Created"),
                            ("transaction_processed", "Transaction Processed"),
                            ("account_accessed", "Account Accessed"),
                            ("security_violation", "Security Violation"),
                            (
                                "system_configuration_changed",
                                "System Configuration Changed",
                            ),
                            ("data_export", "Data Export"),
                            ("data_import", "Data Import"),
                            ("backup_created", "Backup Created"),
                            ("backup_restored", "Backup Restored"),
                            ("session_expired", "Session Expired"),
                            ("account_locked", "Account Locked"),
                            ("account_unlocked", "Account Unlocked"),
                            ("mfa_enabled", "Multi-Factor Authentication Enabled"),
                            ("mfa_disabled", "Multi-Factor Authentication Disabled"),
                            ("mfa_verification_failed", "MFA Verification Failed"),
                            ("suspicious_activity", "Suspicious Activity Detected"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "device_fingerprint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("method", models.CharField(blank=True, max_length=10, null=True)),
                ("endpoint", models.CharField(blank=True, max_length=500, null=True)),
                ("query_params", models.TextField(blank=True, null=True)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "risk_score",
                    models.IntegerField(default=0, help_text="Risk score from 0-100"),
                ),
                (
                    "geolocation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_suspicious", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ImmutableAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA-256 checksum for immutability", max_length=128
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "default_permissions": ("add", "view"),
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("blocked", "Blocked"),
                            ("locked", "Account Locked"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_suspicious", models.BooleanField(default=False)),
                (
                    "geo_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "device_fingerprint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("risk_factors", models.JSONField(blank=True, default=list)),
                ("risk_score", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("otp_code", models.CharField(max_length=6)),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("user_creation", "User Creation"),
                            ("phone_verification", "Phone Verification"),
                            ("transaction", "Transaction Verification"),
                            ("password_reset", "Password Reset"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "house_address",
                    models.TextField(
                        blank=True, help_text="Complete house address", null=True
                    ),
                ),
                (
                    "contact_address",
                    models.TextField(
                        blank=True,
                        help_text="Contact address (if different from house address)",
                        null=True,
                    ),
                ),
                (
                    "government_id",
                    models.CharField(
                        blank=True,
                        help_text="Government-issued ID number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "ssnit_number",
                    models.CharField(
                        blank=True,
                        help_text="Encrypted SSNIT number",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, help_text="Date of birth", null=True),
                ),
                (
                    "employment_date",
                    models.DateField(
                        blank=True, help_text="Employment date", null=True
                    ),
                ),
                (
                    "staff_id",
                    models.CharField(
                        blank=True,
                        help_text="Encrypted staff ID",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "staff_id_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of plain staff ID for uniqueness",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the bank",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Bank account number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "branch_code",
                    models.CharField(
                        blank=True,
                        help_text="Bank branch code",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "routing_number",
                    models.CharField(
                        blank=True,
                        help_text="Bank routing number",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("notify_email", models.BooleanField(default=True)),
                ("notify_sms", models.BooleanField(default=False)),
                ("notify_push", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("passport_picture", "Passport Picture"),
                            ("application_letter", "Copy of Application Letter"),
                            ("appointment_letter", "Copy of Appointment Letter"),
                            ("id_card", "ID Card"),
                            ("utility_bill", "Utility Bill"),
                            ("bank_statement", "Bank Statement"),
                            ("other", "Other Document"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="user_documents/%Y/%m/%d/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("pending_review", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "review_priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 checksum for integrity",
                        max_length=128,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("brute_force", "Brute Force Attack"),
                            ("sql_injection_attempt", "SQL Injection Attempt"),
                            ("xss_attempt", "Cross-Site Scripting Attempt"),
                            ("unauthorized_access", "Unauthorized Access Attempt"),
                            ("privilege_escalation", "Privilege Escalation Attempt"),
                            ("data_breach_attempt", "Data Breach Attempt"),
                            ("session_hijacking", "Session Hijacking Attempt"),
                            ("malware_detection", "Malware Detection"),
                            ("unusual_login_pattern", "Unusual Login Pattern"),
                            ("geographic_anomaly", "Geographic Login Anomaly"),
                            (
                                "multiple_failed_attempts",
                                "Multiple Failed Login Attempts",
                            ),
                            ("account_compromise", "Account Compromise Detected"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("stack_trace", models.TextField(blank=True, null=True)),
                ("action_taken", models.TextField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(
                fields=["phone_number", "-created_at"],
                name="users_otpve_phone_n_a7afd2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(
                fields=["otp_code"], name="users_otpve_otp_cod_281456_idx"
            ),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="immutableauditlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="immutable_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="userdocuments",
            index=models.Index(
                fields=["user", "document_type"], name="users_userd_user_id_d39018_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdocuments",
            index=models.Index(
                fields=["uploaded_at"], name="users_userd_uploade_f4ca5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdocuments",
            index=models.Index(fields=["status"], name="users_userd_status_b2c468_idx"),
        ),
        migrations.AddIndex(
            model_name="userdocuments",
            index=models.Index(
                fields=["is_verified"], name="users_userd_is_veri_5e5c85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdocuments",
            index=models.Index(
                fields=["review_priority"], name="users_userd_review__379db5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userdocuments",
            unique_together={("user", "document_type")},
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(
                fields=["event_type", "-timestamp"],
                name="users_secur_event_t_a225ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(
                fields=["severity", "-timestamp"], name="users_secur_severit_c06d15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(
                fields=["resolved", "-timestamp"], name="users_secur_resolve_d4adc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["email", "-timestamp"], name="users_login_email_9e1a30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["ip_address", "-timestamp"],
                name="users_login_ip_addr_a8b5ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["status", "-timestamp"], name="users_login_status_16d0a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["is_suspicious"], name="users_login_is_susp_18dd46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="immutableauditlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="users_immut_user_id_8ff353_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="immutableauditlog",
            index=models.Index(
                fields=["action", "-timestamp"], name="users_immut_action_2eaf15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="users_audit_user_id_29b33e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "-timestamp"], name="users_audit_action_e79129_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["ip_address", "-timestamp"],
                name="users_audit_ip_addr_2e98e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["is_suspicious"], name="users_audit_is_susp_7afa0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["priority", "-timestamp"], name="users_audit_priorit_6b155d_idx"
            ),
        ),
    ]
