# Generated by Django 5.1 on 2025-12-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('cashier', 'Cashier'), ('mobile_banker', 'Mobile Banker'), ('manager', 'Manager'), ('operations_manager', 'Operations Manager'), ('admin', 'Administrator')], default='customer', max_length=20),
        ),
    ]
