# Generated by Django 4.2 on 2025-10-16 05:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_reset_token_created_at_alter_user_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('verification_type', models.CharField(choices=[('user_creation', 'User Creation'), ('phone_verification', 'Phone Verification'), ('transaction', 'Transaction Verification'), ('password_reset', 'Password Reset')], max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['phone_number', '-created_at'], name='users_otpve_phone_n_a7afd2_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['otp_code'], name='users_otpve_otp_cod_281456_idx'),
        ),
    ]
