# Generated by Django 5.1 on 2025-12-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_limit_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_transaction_limit',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_transaction_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
