# Generated by Django 4.2 on 2025-11-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_phone'),
    ]

    operations = [
    ]
