# Generated by Django 4.2 on 2025-11-20 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer/User'), ('cashier', 'Cashier'), ('mobile_banker', 'Mobile Banker'), ('manager', 'Manager'), ('operations_manager', 'Operations Manager'), ('administrator', 'Administrator')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('brute_force', 'Brute Force Attack'), ('sql_injection_attempt', 'SQL Injection Attempt'), ('xss_attempt', 'Cross-Site Scripting Attempt'), ('unauthorized_access', 'Unauthorized Access Attempt'), ('privilege_escalation', 'Privilege Escalation Attempt'), ('data_breach_attempt', 'Data Breach Attempt'), ('session_hijacking', 'Session Hijacking Attempt'), ('malware_detection', 'Malware Detection'), ('unusual_login_pattern', 'Unusual Login Pattern'), ('geographic_anomaly', 'Geographic Login Anomaly'), ('multiple_failed_attempts', 'Multiple Failed Login Attempts'), ('account_compromise', 'Account Compromise Detected')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('blocked', 'Blocked'), ('locked', 'Account Locked')], max_length=10)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('geo_location', models.CharField(blank=True, max_length=100, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('risk_score', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('failed_login', 'Failed Login'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('role_changed', 'Role Changed'), ('permission_denied', 'Permission Denied'), ('transaction_created', 'Transaction Created'), ('transaction_processed', 'Transaction Processed'), ('account_accessed', 'Account Accessed'), ('security_violation', 'Security Violation'), ('system_configuration_changed', 'System Configuration Changed'), ('data_export', 'Data Export'), ('data_import', 'Data Import'), ('backup_created', 'Backup Created'), ('backup_restored', 'Backup Restored'), ('session_expired', 'Session Expired'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('mfa_enabled', 'Multi-Factor Authentication Enabled'), ('mfa_disabled', 'Multi-Factor Authentication Disabled'), ('mfa_verification_failed', 'MFA Verification Failed'), ('suspicious_activity', 'Suspicious Activity Detected')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=500, null=True)),
                ('query_params', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.IntegerField(default=0, help_text='Risk score from 0-100')),
                ('geolocation', models.CharField(blank=True, max_length=100, null=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', '-timestamp'], name='users_secur_event_t_a225ee_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['severity', '-timestamp'], name='users_secur_severit_c06d15_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['resolved', '-timestamp'], name='users_secur_resolve_d4adc6_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['email', '-timestamp'], name='users_login_email_9e1a30_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip_address', '-timestamp'], name='users_login_ip_addr_a8b5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['status', '-timestamp'], name='users_login_status_16d0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['is_suspicious'], name='users_login_is_susp_18dd46_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='users_audit_user_id_29b33e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='users_audit_action_e79129_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', '-timestamp'], name='users_audit_ip_addr_2e98e5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['is_suspicious'], name='users_audit_is_susp_7afa0f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['priority', '-timestamp'], name='users_audit_priorit_6b155d_idx'),
        ),
    ]
