# Generated by Django 5.1 on 2026-01-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="id_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
