# Generated by Django 5.1.15 on 2026-02-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_id_number_user_id_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id_number_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
    ]
