# Generated by Django 4.2 on 2025-11-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_last_login_alter_user_role_securityevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer/User'), ('cashier', 'Cashier'), ('mobile_banker', 'Mobile Banker'), ('manager', 'Manager'), ('operations_manager', 'Operations Manager'), ('administrator', 'Administrator'), ('superuser', 'Superuser')], default='customer', max_length=20),
        ),
    ]
