# Generated by Django 5.1.15 on 2026-02-06 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_add_password_reset_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
    ]
