# Generated by Django 5.1.15 on 2026-02-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_user_id_number_remove_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id_number_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
