# Generated by Django 5.1.15 on 2026-02-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_user_id_number_hash_user_phone_number_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="staff_id",
        ),
        migrations.AddField(
            model_name="user",
            name="ssnit_number_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="ssnit_number_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="staff_id_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="staff_id_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
