# Generated by Django 5.1 on 2026-03-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_remove_user_first_name_remove_user_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="staff_number",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
