# Generated by Django 6.0.3 on 2026-03-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_alter_useractivity_action_userinvitation"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
