# Generated by Django 6.0.3 on 2026-04-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_user_is_approved"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="adminnotification",
            table="admin_notification",
        ),
        migrations.AlterModelTable(
            name="auditlog",
            table="audit_log",
        ),
        migrations.AlterModelTable(
            name="passwordresettoken",
            table="password_reset_token",
        ),
        migrations.AlterModelTable(
            name="useractivity",
            table="user_activity",
        ),
    ]
