# Generated by Django 6.0.3 on 2026-04-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_adminnotification_table_alter_auditlog_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
