# Generated by Django 6.0.3 on 2026-04-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="key_version",
            field=models.IntegerField(
                default=1, help_text="The version of the encryption key used for PII."
            ),
        ),
    ]
