# Generated by Django 5.1.15 on 2026-04-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_user_key_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_photo_encrypted",
            field=models.TextField(
                blank=True,
                help_text="Encrypted Base64 encoded profile photo",
                null=True,
            ),
        ),
    ]
