# Generated by Django 5.1.15 on 2026-04-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_user_profile_photo_encrypted"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="member_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, null=True, unique=True
            ),
        ),
    ]
