# Generated by Django 5.1.15 on 2026-04-07 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_user_member_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assigned_banker",
            field=models.ForeignKey(
                blank=True,
                help_text="The mobile banker assigned to this customer",
                limit_choices_to={"role": "mobile_banker"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_assigned_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
