# Generated by Django 6.0.3 on 2026-04-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_user_assigned_banker"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="digital_address_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="occupation_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="position_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="work_address_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
    ]
