# Generated by Django 5.1.15 on 2026-04-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_user_date_of_birth_encrypted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
