# Generated by Django 4.2 on 2025-11-20 04:33

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0004_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CheckDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extracted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extracted_account_number', models.CharField(blank=True, max_length=50)),
                ('extracted_routing_number', models.CharField(blank=True, max_length=20)),
                ('extracted_payee', models.CharField(blank=True, max_length=255)),
                ('extracted_date', models.DateField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fraud_flags', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=dict)),
                ('manual_override', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_check_deposits', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_deposit', to='banking.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CheckImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='check_images/%Y/%m/%d/')),
                ('image_type', models.CharField(choices=[('front', 'Front of Check'), ('back', 'Back of Check')], default='front', max_length=10)),
                ('ocr_data', models.JSONField(blank=True, default=dict)),
                ('ocr_processed', models.BooleanField(default=False)),
                ('ocr_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='banking.checkdeposit')),
            ],
            options={
                'unique_together': {('check_deposit', 'image_type')},
            },
        ),
    ]
