# Generated by Django 4.2 on 2025-11-20 05:00

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0006_transaction_category_transaction_reference_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDrawer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_start', models.DateTimeField(blank=True, null=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('open', 'Open'), ('reconciled', 'Reconciled'), ('discrepancy', 'Discrepancy')], default='closed', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('opening_denominations', models.JSONField(blank=True, default=dict)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('closing_denominations', models.JSONField(blank=True, default=dict)),
                ('expected_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('actual_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_drawers', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_drawers', to='banking.branch')),
            ],
            options={
                'ordering': ['-session_start'],
                'unique_together': {('branch', 'assigned_cashier', 'session_start')},
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('deposit', 'Cash Deposit'), ('withdrawal', 'Cash Withdrawal'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('fee_collection', 'Fee Collection'), ('change_fund', 'Change Fund'), ('opening_balance', 'Opening Balance'), ('closing_balance', 'Closing Balance')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('denominations', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('cash_drawer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='banking.cashdrawer')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transaction', to='banking.transaction')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='CashReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reconciliation_date', models.DateField(default=datetime.date.today)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_closing_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_closing_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_transfers_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_transfers_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('variance_reason', models.TextField(blank=True)),
                ('variance_category', models.CharField(blank=True, max_length=50)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.branch')),
                ('cash_drawer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation', to='banking.cashdrawer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reconciliation_date', '-created_at'],
                'unique_together': {('cash_drawer', 'reconciliation_date')},
            },
        ),
    ]
