# Generated by Django 4.2 on 2025-11-20 05:31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0007_cashdrawer_cashtransaction_cashreconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('closure_reason', models.CharField(choices=[('customer_request', 'Customer Request'), ('fraud_suspected', 'Fraud Suspected'), ('deceased', 'Account Holder Deceased'), ('compliance', 'Compliance Violation'), ('inactive', 'Account Inactive'), ('other', 'Other')], max_length=20)),
                ('other_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under Review'), ('balance_check', 'Balance Check'), ('pending_settlement', 'Pending Settlement'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('balance_at_closure', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('outstanding_loans', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pending_transactions', models.IntegerField(default=0)),
                ('settlement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('settlement_method', models.CharField(blank=True, max_length=50)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_date', models.DateField(blank=True, null=True)),
                ('documents', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closure_requests', to='banking.account')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_closures', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_closures', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closure_requests', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_closures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountOpening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('savings', 'Savings Account'), ('checking', 'Checking Account'), ('business', 'Business Account'), ('joint', 'Joint Account')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('identity_verification', 'Identity Verification'), ('document_review', 'Document Review'), ('compliance_check', 'Compliance Check'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=25)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('identity_verified', models.BooleanField(default=False)),
                ('identity_verified_at', models.DateTimeField(blank=True, null=True)),
                ('documents', models.JSONField(default=dict)),
                ('document_verified', models.BooleanField(default=False)),
                ('document_verified_at', models.DateTimeField(blank=True, null=True)),
                ('compliance_checked', models.BooleanField(default=False)),
                ('compliance_checked_at', models.DateTimeField(blank=True, null=True)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('regulatory_flags', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('account_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_application', to='banking.account')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_openings', to=settings.AUTH_USER_MODEL)),
                ('compliance_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_checks', to=settings.AUTH_USER_MODEL)),
                ('document_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_verifications', to=settings.AUTH_USER_MODEL)),
                ('identity_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_verifications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('account_opening', 'Account Opening'), ('account_update', 'Account Update'), ('transaction', 'High-Value Transaction'), ('loan_application', 'Loan Application'), ('manual', 'Manual Verification')], max_length=20)),
                ('verification_method', models.CharField(choices=[('document', 'Document Verification'), ('biometric', 'Biometric Verification'), ('database', 'Database Check'), ('third_party', 'Third Party Verification'), ('manual', 'Manual Verification')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('identity_number', models.CharField(blank=True, max_length=50)),
                ('identity_type', models.CharField(blank=True, max_length=50)),
                ('verification_data', models.JSONField(default=dict)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_result', models.JSONField(default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('geotag', models.CharField(blank=True, max_length=100)),
                ('account_opening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity_verifications', to='banking.accountopening')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_verification_records', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountClosureAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('requested', 'Closure Requested'), ('verified', 'Closure Verified'), ('approved', 'Closure Approved'), ('rejected', 'Closure Rejected'), ('processed', 'Closure Processed'), ('closed', 'Account Closed'), ('cancelled', 'Closure Cancelled')], max_length=20)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('closure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='banking.accountclosure')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='identityverification',
            index=models.Index(fields=['status'], name='banking_ide_status_e57fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='identityverification',
            index=models.Index(fields=['verification_type'], name='banking_ide_verific_6ac0cb_idx'),
        ),
        migrations.AddIndex(
            model_name='identityverification',
            index=models.Index(fields=['user'], name='banking_ide_user_id_17c893_idx'),
        ),
        migrations.AddIndex(
            model_name='identityverification',
            index=models.Index(fields=['verified'], name='banking_ide_verifie_a97b93_idx'),
        ),
        migrations.AddIndex(
            model_name='accountopening',
            index=models.Index(fields=['status'], name='banking_acc_status_1889f3_idx'),
        ),
        migrations.AddIndex(
            model_name='accountopening',
            index=models.Index(fields=['applicant'], name='banking_acc_applica_1b19f4_idx'),
        ),
        migrations.AddIndex(
            model_name='accountopening',
            index=models.Index(fields=['identity_verified'], name='banking_acc_identit_8e4969_idx'),
        ),
        migrations.AddIndex(
            model_name='accountopening',
            index=models.Index(fields=['compliance_checked'], name='banking_acc_complia_aa44ff_idx'),
        ),
        migrations.AddIndex(
            model_name='accountclosureaudit',
            index=models.Index(fields=['closure'], name='banking_acc_closure_f5a7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='accountclosureaudit',
            index=models.Index(fields=['action'], name='banking_acc_action_1b6c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='accountclosureaudit',
            index=models.Index(fields=['performed_by'], name='banking_acc_perform_a46173_idx'),
        ),
        migrations.AddIndex(
            model_name='accountclosure',
            index=models.Index(fields=['status'], name='banking_acc_status_8dbb48_idx'),
        ),
        migrations.AddIndex(
            model_name='accountclosure',
            index=models.Index(fields=['account'], name='banking_acc_account_6cef5b_idx'),
        ),
        migrations.AddIndex(
            model_name='accountclosure',
            index=models.Index(fields=['requested_by'], name='banking_acc_request_5e3392_idx'),
        ),
        migrations.AddIndex(
            model_name='accountclosure',
            index=models.Index(fields=['closure_reason'], name='banking_acc_closure_e963cf_idx'),
        ),
    ]
