name: API-Linting-Workflow

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  schedule:
    - cron: '38 2 * * 6'

permissions:
  contents: read

jobs:
  lint-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Run Spectral Linter
        run: npx @stoplight/spectral-cli lint banking_backend/schema.yml
